// Runtime v2 independent boundary audit. Run through ../runtime-v2.mjs.
const {outputDir, productFile, browserPath, makeRegressionProject} = require('./config.cjs');
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto');
const {loadApi}=require('../../browser/cases/audit-lib.cjs');
const product=productFile,html=fs.readFileSync(product,'utf8'),A=loadApi(html),reports=[];
const N=value=>({kind:'NumberLiteral',value}),S=value=>({kind:'StringLiteral',value}),B=value=>({kind:'BooleanLiteral',value}),Q=(value,unit)=>({kind:'QuantityLiteral',value:N(value),unit}),V=name=>({kind:'VariableRead',name}),self={kind:'self'},dog={kind:'named',name:'いぬ'},cat={kind:'named',name:'ねこ'},say=(value,actorRef=self)=>({kind:'Say',value,actorRef}),wait=seconds=>({kind:'WaitTime',seconds:Q(seconds,'秒'),actorRef:self}),fn=(name,args=[],argumentNames=[])=>({kind:'UserFunctionCall',name,args,argumentNames}),sub=(left,right)=>({kind:'BinaryExpression',op:'SUB',left,right});
function test(id,body){try{const details=body();reports.push({id,pass:true,details});console.log('PASS',id)}catch(e){reports.push({id,pass:false,detail:e.stack});console.error('FAIL',id,e.message)}}
function project(){const p=makeRegressionProject(A),sprite=p.components.find(x=>x.type==='sprite'),input={...structuredClone(p.components.find(x=>x.type==='button')),type:'input'};p.name='Runtime v2 boundary';p.components=[{...structuredClone(sprite),id:'cat',name:'ねこ',x:0,y:0,direction:0},{...structuredClone(sprite),id:'dog',name:'いぬ',x:100,y:0,direction:0},{...structuredClone(input),id:'entry',name:'入力欄1',text:'go'}];p.components.forEach(x=>{x.localData={variables:[],lists:[]};if(x.costumes){x.costumes=[{id:'costume-'+x.id,name:'顔',kind:'text',value:'🐈'}];x.costumeId='costume-'+x.id;}});p.scripts=[];p.actions=[];p.functions=[];return p}
function env(p=project(),items=[]){const r=new A.RuntimeModel(p,{}),c={items,astByKey:new Map(items.map(x=>[x.key,x.ast])),symbols:{actions:new Map(p.actions.map(x=>[x.name,x])),functions:new Map(p.functions.map(x=>[x.name,x]))}},out=[];let clock=0;r.now=()=>clock;r.pauseClock=()=>{};r.resumeClock=()=>{};const q=new A.EventScheduler(p,c,r,{say:(id,value)=>out.push([id,value])});q.schedule=()=>{};return{p,r,c,q,out,time:t=>clock=t,ctx:{runtime:r,compiled:c,runtimeId:'cat',eventContext:{}},drain(){for(let i=0;i<5000&&q.ready.length;i++)q.runTurn()}}}
const fdef={id:'difference',ownerId:'stage',name:'差',args:['a','b']},readdef={id:'read',ownerId:'stage',name:'位置',args:[]};
test('NAMED-FUNCTION-SOURCE-ORDER-AND-QUANTITY',()=>{const p=project();p.functions=[fdef];const e=env(p,[{key:'function:difference',ast:{kind:'Script',body:[{kind:'ReturnStatement',value:sub(V('a'),V('b'))}]}}]);let calls=0;e.r.prng.nextFloat=()=>[.1,.7][calls++];const rand={kind:'BuiltinCall',name:'乱数',args:[N(0),N(9)]};assert.equal(A.evalExpression(fn('差',[rand,rand],['b','a']),e.ctx),6);assert.equal(calls,2);const value=A.evalExpression(fn('差',[Q(3,'歩'),Q(10,'歩')],['b','a']),e.ctx);assert.equal(value.magnitude,7);assert.equal(value.unit,'歩');for(const names of [['a','a'],['a','missing'],['a']])assert.throws(()=>A.evalExpression(fn('差',[N(1),N(2)],names),e.ctx),x=>x.code==='S308');return{sourceOrderDraws:calls,result:value}});
test('QUALIFIED-FUNCTION-SUBJECT-AND-CALLER-RESTORATION',()=>{const p=project();p.functions=[readdef];const e=env(p,[{key:'function:read',ast:{kind:'Script',body:[{kind:'ReturnStatement',actorRef:self,value:{kind:'SensorRead',sensor:'横位置'}}]}}]);const own=A.evalExpression(fn('位置'),e.ctx),other=A.evalExpression({kind:'ActorQualifiedRead',actorRef:dog,value:fn('位置')},e.ctx),after=A.evalExpression(fn('位置'),e.ctx);assert.equal(own.magnitude,0);assert.equal(other.magnitude,100);assert.equal(after.magnitude,0);assert.equal(e.ctx.runtimeId,'cat');e.c.astByKey.set('function:read',{kind:'Script',body:[{kind:'ReturnStatement',actorRef:dog,value:{kind:'SensorRead',sensor:'横位置'}}]});assert.equal(A.evalExpression(fn('位置'),e.ctx).magnitude,100);return{own,other,after}});
function payloadFixture(){const p=project();p.projectData.variables=[{id:'distance',name:'距離',initialValue:{magnitude:7,unit:'歩'},expectedUnit:'歩'}];p.projectData.lists=[];p.scripts=[{id:'start-a',targetId:'cat',event:'start',source:'何もしない。'},{id:'start-b',targetId:'cat',event:'start',source:'何もしない。'},{id:'key-right',targetId:'cat',event:'keyDown',filter:{key:'右'},source:'何もしない。'},{id:'key-left',targetId:'cat',event:'keyDown',filter:{key:'左'},source:'何もしない。'},{id:'message-go',targetId:'dog',event:'message',filter:{message:'go'},source:'何もしない。'},{id:'input-change',targetId:'entry',event:'valueChanged',source:'何もしない。'}];const data=A.packExecutable(p);const by=id=>data.program.find(x=>x.id===id);by('start-a').ast={kind:'Script',body:[say({kind:'SensorRead',sensor:'KEY_DOWN',arg:S('右')}),say(V('距離'),dog)],rules:[{kind:'ContinuousRule',condition:{kind:'SensorRead',sensor:'KEY_DOWN',arg:S('右')},actorRef:cat,direction:'right',seconds:Q(1,'秒'),distance:Q(20,'歩')}]};by('start-b').ast={kind:'Script',body:[{kind:'Broadcast',message:S('go'),actorRef:self}]};by('key-right').ast={kind:'Script',body:[say(S('RIGHT'))]};by('key-left').ast={kind:'Script',body:[say(S('LEFT'))]};by('message-go').ast={kind:'Script',body:[say(S('MESSAGE'))]};by('input-change').ast={kind:'Script',body:[say({kind:'SensorRead',sensor:'新しい値'})]};return{p,data}}
const packed=payloadFixture();
test('RESTORE-SCRIPT-ID-EVENT-FILTER-RULES-QUANTITY',()=>{const restored=A.restoreExecutable(structuredClone(packed.data));assert.equal(restored.compiled.items.length,6);assert.equal(restored.compiled.rules.length,1);assert.equal(restored.compiled.rules[0].actorRef.name,'ねこ');assert.equal(restored.compiled.rules[0].distance.unit,'歩');assert.equal(restored.project.projectData.variables[0].initialValue.unit,'歩');const r=new A.RuntimeModel(restored.project,{});let clock=0;r.now=()=>clock;const out=[],q=new A.EventScheduler(restored.project,restored.compiled,r,{say:(id,v)=>out.push([id,v])});q.schedule=()=>{};r.pressedKeys.add('右');q.start();for(let i=0;i<40&&q.ready.length;i++)q.runTurn();q.spawnDistributed('keyDown',{key:'右'});for(let i=0;i<40&&q.ready.length;i++)q.runTurn();assert.ok(out.some(x=>x[1]==='RIGHT'));assert.ok(!out.some(x=>x[1]==='LEFT'));assert.ok(out.some(x=>x[1]==='MESSAGE'));clock=500;q.advanceContinuous();assert.ok(Math.abs(r.actor('cat').x-10)<1e-8);assert.equal(q.seq,4);q.stop();return{out,ruleId:restored.compiled.rules[0].id}});
test('RESTORE-REJECTS-CORRUPT-QUANTITY-AND-ID',()=>{for(const mutate of [d=>d.program[0].id='wrong',d=>d.program[0].event='missing',d=>d.program[0].ast.rules[0].distance.unit='unknown',d=>d.project.projectData.variables[0].initialValue={magnitude:1,unit:'秒'}]){const d=structuredClone(packed.data);mutate(d);assert.throws(()=>A.restoreExecutable(d));}});
test('RESTORE-REJECTS-CORRUPT-FILTER',()=>{const d=structuredClone(packed.data);d.program.find(x=>x.id==='key-right').filter={message:'wrong kind'};assert.throws(()=>A.restoreExecutable(d));});
test('RESTORE-REJECTS-CORRUPT-RULE-DIRECTION',()=>{const d=structuredClone(packed.data);d.program[0].ast.rules[0].direction='unknown';assert.throws(()=>A.restoreExecutable(d));});
test('RESTORED-TASK-LIMIT-REMAINS-2000',()=>{const data=structuredClone(packed.data);data.program=data.program.filter(x=>x.id==='key-right');data.program[0].ast.body=[wait(100)];const restored=A.restoreExecutable(data),r=new A.RuntimeModel(restored.project,{}),q=new A.EventScheduler(restored.project,restored.compiled,r,{});q.running=true;q.schedule=()=>{};for(let i=0;i<2000;i++)q.spawnDistributed('keyDown',{key:'右'});assert.equal(q.tasks.size,2000);assert.throws(()=>q.spawnDistributed('keyDown',{key:'右'}),e=>e.code==='R413');q.stop();assert.equal(q.tasks.size,0);return{limit:2000}});
// Direct AST fixture uses the generated standalone's exact runtime/stage/player functions.
function savePlayer(name,data,options={}){let player=A.generateStandaloneHtml(packed.p);const marker='mountAkariPlayer(createAkariRuntime(),createAkariStageView,',start=player.lastIndexOf(marker),end=player.indexOf(');',start);assert.ok(start>=0&&end>start);const json=JSON.stringify(data).replace(/[<>&\u2028\u2029]/g,c=>'\\u'+c.charCodeAt(0).toString(16).padStart(4,'0'));const spy=`const auditCore=createAkariRuntime();const auditStart=auditCore.EventScheduler.prototype.start;auditCore.EventScheduler.prototype.start=function(...args){globalThis.__auditScheduler=this;globalThis.__auditSays=[];const say=this.ui.say;this.ui.say=(...values)=>{__auditSays.push(values);return say?.(...values)};if(globalThis.__fixedClock){this.runtime.now=()=>globalThis.__logicalClock;}return auditStart.apply(this,args)};mountAkariPlayer(auditCore,createAkariStageView,`;
player=player.slice(0,start)+spy+json+player.slice(end);fs.writeFileSync(path.join(outputDir,name+'.html'),player)}
savePlayer('player-key',packed.data);
const functionData=structuredClone(packed.data);functionData.program=functionData.program.filter(x=>x.id==='start-a');functionData.project.functions=[fdef,readdef];delete functionData.program[0].ast.rules;functionData.program[0].ast.body=[say({kind:'BuiltinCall',name:'つなぐ',args:[S('named='),fn('差',[Q(3,'歩'),Q(10,'歩')],['b','a']),S('; other='),{kind:'ActorQualifiedRead',actorRef:dog,value:fn('位置')},S('; self='),fn('位置')]})];functionData.program.push({key:'function:difference',ownerId:'stage',ast:{kind:'Script',body:[{kind:'ReturnStatement',value:sub(V('a'),V('b'))}]}},{key:'function:read',ownerId:'stage',ast:{kind:'Script',body:[{kind:'ReturnStatement',actorRef:self,value:{kind:'SensorRead',sensor:'横位置'}}]}});savePlayer('player-functions',functionData);
const inputData=structuredClone(packed.data);inputData.program=inputData.program.filter(x=>['start-a','input-change'].includes(x.id));inputData.program[0].ast.body=[];inputData.program[0].ast.rules[0].condition={kind:'CompareExpression',op:'EQ',left:{kind:'SensorRead',sensor:'INPUT_VALUE',arg:S('入力欄1')},right:S('go')};savePlayer('player-input',inputData);
const askData=structuredClone(packed.data);askData.program=askData.program.filter(x=>['start-a','start-b'].includes(x.id));delete askData.program[0].ast.rules;askData.program[0].ast.body=[{kind:'Ask',question:S('one'),actorRef:dog},say(S('AFTER-ONE'))];askData.program[1].ast.body=[{kind:'Ask',question:S('two'),actorRef:cat},say(S('AFTER-TWO'))];savePlayer('player-ask',askData);
const audioData=structuredClone(askData);audioData.program[0].ast.body=[{kind:'SoundCommand',op:'TONE_WAIT',args:[Q(440,'Hz'),Q(5,'秒')],actorRef:dog},say(S('AFTER-AUDIO'))];audioData.program[1].ast.body=[{kind:'Ask',question:S('stop all?'),actorRef:cat},say(S('AFTER-ASK'))];savePlayer('player-audio-ask',audioData);
fs.writeFileSync(path.join(outputDir,'payload.json'),JSON.stringify(packed.data,null,2));fs.writeFileSync(path.join(outputDir,'node-evidence.json'),JSON.stringify({productSha256:crypto.createHash('sha256').update(html).digest('hex'),reports},null,2));if(reports.some(x=>!x.pass))process.exitCode=1;
