import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import {currentProductFile} from '../lib/product-path.cjs';
import {snapshot,sha,withBrowser,pageFor} from '../lib/product-test-host.mjs';
import {loadApi} from '../browser/cases/audit-lib.cjs';
import {samplesFeature,sampleTestIds,sampleExpected,verifySamples} from '../lib/samples-contract.mjs';
import {browserEnvironment} from '../lib/browser-environment.mjs';
const require=createRequire(import.meta.url),[chrome,outputArg]=process.argv.slice(2),output=path.resolve(outputArg),dir=output.replace(/\.json$/,'')+'.artifacts',product=currentProductFile();
fs.mkdirSync(dir,{recursive:true});fs.copyFileSync(product,path.join(dir,'candidate.html'));
const inputs=snapshot(product),A=loadApi(fs.readFileSync(product,'utf8')),plain=x=>JSON.parse(JSON.stringify(x));
const report={schema:'akari-samples-evidence-v1',status:'RUNNING',snapshot:inputs,environment:{browser:null,playwright:require('playwright/package.json').version},pageErrors:[],networkRequests:[],results:[],artifacts:[]};
const save=()=>fs.writeFileSync(output,JSON.stringify(report,null,2)+'\n');
async function row(id,fn){const result={id,status:'RUNNING'};report.results.push(result);try{await fn();result.status='PASS';result.observed=sampleExpected[id];}catch(e){result.status='FAIL';result.error=e.stack;console.error(e.stack);}save();console.log(result.status+' '+id);}
function nodeRuntime(id){const p=A.makeSampleProject(id),original=JSON.stringify(p),r=new A.RuntimeModel(p,{});let clock=0;const speech=[],lines=[],errors=[],jumps=[],previous=new Map();r.now=()=>clock;const s=new A.EventScheduler(p,A.compileProject(p),r,{say:(id,text)=>speech.push([id,text]),penLine:(...args)=>lines.push(args),runtimeError:(t,e)=>errors.push(e.message)});s.schedule=()=>{};const pump=()=>{let n=0;while(s.ready.length&&n++<1000)s.runTurn(true);assert.ok(n<1000);assert.deepEqual(errors,[]);};const advance=until=>{for(;clock<=until;clock+=10){s.advanceContinuous(clock);s.recheckBlocked(true);pump();if(id==='dance')for(const actor of ['sprite-1','dango']){const y=r.actor(actor).y;if(y<141&&(previous.get(actor)??200)>=141)jumps.push(actor);previous.set(actor,y);}}};s.start();pump();return{p,r,s,speech,lines,jumps,pump,advance,unchanged:()=>assert.equal(JSON.stringify(p),original)};}
await row('SAMPLES-CATALOG',async()=>{
 const productSource=fs.readFileSync(product,'utf8');assert.ok(productSource.includes("const modelLocked = () => appState !== 'DESIGN' || !!runtime || !!scheduler;"));assert.ok(/function updateEditingLock\(\)[\s\S]{0,450}'sampleSelect'/.test(productSource));
 const manifest=JSON.parse(fs.readFileSync('audit/manifests/samples.json'));assert.deepEqual(manifest.feature,samplesFeature);assert.deepEqual(manifest.testIds,sampleTestIds);
 assert.deepEqual(plain(A.sampleCatalog().map(x=>x.id)),samplesFeature.ids);assert.deepEqual(plain(A.sampleCatalog().map(x=>x.label.replace(/^お手本[①②③] /,''))),samplesFeature.names);
 for(const id of samplesFeature.ids){const p=A.makeSampleProject(id),store=A.makeSampleAssetStore(id);assert.deepEqual(plain(A.compileProject(p).errors),[]);assert.equal(p.components[0].name,'マスコット');assert.equal(p.scripts.length,id==='game'?2:1);
  for(const script of p.scripts){const parsed=A.parseSyntax(script.source,{targetId:script.targetId,event:script.event,symbols:A.buildSymbols(p)});assert.ok(parsed.ast);const codec=A.blockEncode(parsed.ast);assert.ok(A.astEquivalent(parsed.ast,A.blockDecode(codec.tree)));}
  for(const asset of store.snapshotRefs().values()){assert.equal(A.sha256Fallback(asset.bytes),asset.sha256);assert.ok(A.collectReachableAssetIds(p).has(asset.id));}
  p.components[0].x=-999;p.scripts[0].source='bad';assert.notEqual(A.makeSampleProject(id).components[0].x,-999);assert.deepEqual(plain(A.compileProject(A.makeSampleProject(id)).errors),[]);
 }
 assert.equal(A.makeSampleAssetStore('dance').snapshotRefs().size,2);assert.equal(A.makeSampleAssetStore('flower').snapshotRefs().size,1);assert.equal(A.makeSampleAssetStore('game').snapshotRefs().size,1);
 assert.throws(()=>A.makeSampleProject('missing'));assert.ok(A.makeEmptyProject().scripts.every(s=>!s.source));
});
await row('SAMPLES-RUNTIME',async()=>{
 const d=nodeRuntime('dance');try{d.advance(15000);assert.deepEqual(d.jumps,['sprite-1','dango','sprite-1','dango']);assert.deepEqual(d.speech.map(x=>x[1]),['いっしょに おどろう！','きまった！','もういちど おどろう！']);for(const [id,x]of [['sprite-1',120],['dango',420]]){assert.equal(d.r.actor(id).x,x);assert.equal(d.r.actor(id).y,200);assert.equal(d.r.actor(id).direction,0);}assert.equal(d.speech.filter(x=>x[1]==='きまった！').length,1);d.unchanged();}finally{d.s.stop();}
 const f=nodeRuntime('flower');try{f.advance(10000);assert.equal(f.lines.length,36);for(let i=0;i<12;i++){const start=f.lines[i*3],end=f.lines[i*3+2];assert.ok(Math.abs(start[0]-end[2])<1e-7&&Math.abs(start[1]-end[3])<1e-7);}assert.equal(f.r.actor('sprite-1').x,40);assert.equal(f.r.actor('sprite-1').y,280);f.unchanged();}finally{f.s.stop();}
 for(let restart=0;restart<2;restart++){const g=nodeRuntime('game');try{assert.equal(g.r.projectVars.get('点数'),0);assert.equal(g.r.actor('star').visible,true);for(let i=1;i<=5;i++){g.s.spawnMatching('star','star','click',{});g.pump();assert.equal(g.r.projectVars.get('点数'),i);assert.match(g.r.actor('score').text,new RegExp(String(i)));if(i<5){const star=g.r.actor('star');assert.ok(star.x>=140&&star.x<=520&&star.y>=120&&star.y<=280);}}g.s.spawnMatching('star','star','click',{});g.pump();assert.equal(g.r.projectVars.get('点数'),5);assert.equal(g.r.actor('star').visible,false);assert.equal(g.r.projectVars.get('受付'),0);g.advance(6000);assert.equal(g.speech.filter(x=>x[1]==='やったね！ ぜんぶ つかまえた！').length,1);assert.equal(g.r.actor('sprite-1').direction,360);g.unchanged();}finally{g.s.stop();}}
});
const fingerprint=page=>page.evaluate(()=>({project:JSON.stringify(Akari.app.project),editor:JSON.stringify(Akari.app.editorState),source:document.querySelector('#codeEditor').value}));
async function open(page,id){await page.locator('#sampleSelect').selectOption(id);await page.locator('#sampleBtn').click();assert.equal(await page.locator('#sampleConfirm').evaluate(e=>e.open),true);await page.locator('#sampleConfirmYes').click();await page.waitForFunction(name=>Akari.app.project.name===name,samplesFeature.names[samplesFeature.ids.indexOf(id)]);}
async function source(page){return page.evaluate(()=>Akari.app.editorState.main.sourceText);}
async function command(page,node,action){const menu=node.locator(':scope > .blockui-node-head .blockui-actions');await menu.locator('summary').click();await menu.locator('[data-blockui-action="'+action+'"]').click();}
async function checkHistory(page,before){const after=await source(page);assert.notEqual(after,before);await page.locator('#undoBtn').click();assert.equal(await source(page),before);await page.locator('#redoBtn').click();assert.equal(await source(page),after);await page.locator('#undoBtn').click();return after;}
try{await withBrowser(chrome,async browser=>{
 report.environment.browser=browser.version();assert.equal(browser.version(),browserEnvironment.version);assert.equal(report.environment.playwright,browserEnvironment.playwright);
 const test=(id,fn)=>row(id,()=>pageFor(browser,product,async page=>{page.setDefaultTimeout(10000);page.on('dialog',d=>d.accept());page.on('pageerror',e=>report.pageErrors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))report.networkRequests.push(r.url());});await page.setViewportSize({width:1366,height:900});try{return await fn(page);}catch(e){await page.screenshot({path:path.join(dir,'failure-'+id+'.png')}).catch(()=>{});throw e;}}));
 await test('SAMPLES-CHOICE-CONFIRM',async page=>{
  const original=await fingerprint(page);for(const id of samplesFeature.ids){await page.locator('#sampleSelect').selectOption(id);assert.deepEqual(await fingerprint(page),original);}
  for(const level of ['basic','advanced'])for(const mode of ['code','blocks'])for(const id of samplesFeature.ids){await page.locator('#uiLevel').selectOption(level);await page.locator('#editorMode'+mode).click();await open(page,id);assert.equal(await page.locator('#uiLevel').inputValue(),level);assert.equal(await page.locator('#editorMode'+mode).getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#objectSelect').inputValue(),id==='game'?'star':'sprite-1');assert.equal(await page.locator('#eventSelect').inputValue(),id==='game'?'click':'start');}
 });
 await test('SAMPLES-CANCEL-PENDING',async page=>{
  await open(page,'flower');await page.locator('#uiLevel').selectOption('advanced');await page.locator('#editorModecode').click();await page.locator('#codeEditor').fill('マスコットは書きかけの');await page.waitForTimeout(400);const code=await fingerprint(page);await page.locator('#sampleBtn').click();await page.locator('#sampleConfirmCancel').click();assert.deepEqual(await fingerprint(page),code);await page.locator('#sampleBtn').click();await page.keyboard.press('Escape');assert.deepEqual(await fingerprint(page),code);
  await open(page,'flower');await page.locator('#editorModeblocks').click();const number=page.locator('#blockEditor .blockui-node[data-schema-id="NumberLiteral"] input[data-blockui-field="value"]').first();await number.fill('bad');await number.press('Enter');const block=await fingerprint(page);await page.locator('#sampleSelect').selectOption('game');assert.deepEqual(await fingerprint(page),block);await page.locator('#sampleBtn').click();await page.locator('#sampleConfirmCancel').click();assert.deepEqual(await fingerprint(page),block);assert.equal(await number.inputValue(),'bad');
  await open(page,'dance');await page.locator('#procBtn').click();await page.locator('#callableType').selectOption('action');await page.locator('#callableName').fill('書きかけ');await page.locator('#callableName').press('Tab');await page.waitForTimeout(400);const draft=await fingerprint(page);await page.locator('#procClose').click();const closed=await fingerprint(page);await page.locator('#sampleBtn').click();await page.locator('#sampleConfirmCancel').click();assert.deepEqual(await fingerprint(page),closed);assert.deepEqual(JSON.parse((await fingerprint(page)).editor).callableDraft,JSON.parse(draft.editor).callableDraft);
 });
 await test('SAMPLES-RESET-ISOLATION',async page=>{
  for(const from of samplesFeature.ids)for(const to of samplesFeature.ids.filter(x=>x!==from)){await open(page,from);await page.locator('#editorModecode').click();await page.locator('#codeEditor').fill((await source(page))+'\nマスコットは「改造中」と言う。');await page.waitForTimeout(100);await open(page,to);assert.deepEqual(await page.evaluate(()=>JSON.parse(JSON.stringify(Akari.app.project))),plain(A.makeSampleProject(to)));assert.equal(await page.locator('#undoBtn').isDisabled(),true);assert.equal(await page.locator('#redoBtn').isDisabled(),true);}
  await open(page,'dance');const original=await source(page);await page.locator('#codeEditor').fill(original+'\nマスコットは「変更」と言う。');await page.waitForTimeout(300);await open(page,'dance');assert.equal(await source(page),original);await page.waitForTimeout(1600);assert.equal(await page.evaluate(()=>Akari.app.editorState.history),1);assert.equal(await page.evaluate(()=>Akari.app.editorState.dirty),false);assert.equal(await page.evaluate(()=>Object.keys(localStorage).filter(k=>/autosave|fallback/.test(k)).some(k=>localStorage.getItem(k)?.includes('変更'))),false);await page.reload();await page.waitForFunction(()=>!!Akari.app);assert.ok(await page.evaluate(()=>Akari.app.project.scripts.every(s=>!s.source)));
 });
 await test('SAMPLES-BLOCK-EDIT',async page=>{
  await page.locator('#uiLevel').selectOption('advanced');
  for(const id of samplesFeature.ids){await open(page,id);await page.locator('#editorModeblocks').click();const original=await source(page);const number=page.locator('#blockEditor .blockui-node[data-schema-id="NumberLiteral"] input[data-blockui-field="value"]').first();const value=await number.inputValue();await number.fill(String(Number(value)+1));await number.press('Enter');await checkHistory(page,original);
   const statement=()=>id==='game'?page.locator('#blockEditor .blockui-node[data-schema-id="Assignment"]').first():page.locator('#blockEditor .blockui-script > .blockui-node-content > .blockui-body > .blockui-node').first();
   await command(page,statement(),'replace-noop');assert.ok(await page.locator('#blockEditor [data-schema-id="NoOperation"]').count());await checkHistory(page,original);
   await command(page,statement(),'move-down');await checkHistory(page,original);
   await command(page,statement(),'remove');await checkHistory(page,original);
   const insert=page.locator('#blockEditor .blockui-script > .blockui-node-content > .blockui-body > [data-blockui-action="body-insert"]').last();await insert.click();const search=page.locator('#blockEditor [data-blockui-search]:visible').first();await search.fill('言う');await page.locator('#blockEditor [data-blockui-action="palette-add"][data-blockui-schema="Say"]:visible').first().click();const added=await checkHistory(page,original);assert.match(added,/こんにちは/);
   assert.deepEqual(await page.evaluate(()=>Akari.app.compile().errors.map(e=>e.message)),[]);await page.locator('#editorModecode').click();assert.equal(await page.locator('#codeEditor').inputValue(),original);await page.locator('#editorModeblocks').click();assert.equal(await source(page),original);
  }
 });
 await test('SAMPLES-SAVE-OFFLINE',async page=>{
  for(const id of samplesFeature.ids){await open(page,id);const initial=await page.evaluate(()=>JSON.stringify(Akari.app.project));await page.locator('#runBtn').click();
   if(id==='game'){for(let score=1;score<=5;score++){await page.locator('#formSurface .component[data-id="star"]').click();await page.waitForFunction(n=>document.querySelector('#formSurface .component[data-id="score"]')?.textContent.includes(String(n)),score);}await page.waitForFunction(()=>document.querySelector('#formSurface .component[data-id="star"]').style.display==='none');}
   else{const phrase=id==='dance'?'もういちど おどろう！':'できた！';await page.waitForFunction(text=>[...document.querySelectorAll('.sprite-bubble')].some(x=>x.textContent.includes(text)),phrase,{timeout:25000});if(id==='flower')assert.ok(await page.locator('#penCanvas').evaluate(c=>c.getContext('2d').getImageData(0,0,c.width,c.height).data.some((v,i)=>i%4===3&&v>0)));}
   await page.screenshot({path:path.join(dir,id+'.png')});await page.locator('#stopBtn').click();assert.equal(await page.evaluate(()=>JSON.stringify(Akari.app.project)),initial);
   await page.locator('#editorModecode').click();await page.locator('#codeEditor').fill((await source(page))+'\nマスコットは「お手本の改造保存」と言う。');await page.locator('#editorModeblocks').click();const changed=await page.evaluate(()=>JSON.stringify(Akari.app.project));
   const download=page.waitForEvent('download');await page.locator('#saveBtn').click();const saved=await download;assert.ok(saved.suggestedFilename().endsWith('.akari.md'));await saved.saveAs(path.join(dir,id+'.akari.md'));assert.equal(await saved.failure(),null);
   await page.locator('#fileInput').setInputFiles(path.join(dir,id+'.akari.md'));await page.waitForFunction(text=>Akari.app.editorState.state==='DESIGN'&&JSON.stringify(Akari.app.project)===text&&Akari.app.editorState.main.sourceText.includes('お手本の改造保存'),changed);assert.equal(await source(page),JSON.parse(changed).scripts.find(s=>s.targetId===(id==='game'?'star':'sprite-1')&&s.event===(id==='game'?'click':'start')).source);
   const exported=page.waitForEvent('download');await page.locator('#exportBtn').click();await page.locator('#exportControls').click();const player=await exported;await player.saveAs(path.join(dir,id+'-player.html'));assert.equal(await player.failure(),null);
   const context=await browser.newContext({offline:true});await context.route(/^https?:/,r=>{report.networkRequests.push(r.request().url());return r.abort();});const p=await context.newPage();p.on('pageerror',e=>report.pageErrors.push(e.message));try{await p.goto(pathToFileURL(path.join(dir,id+'-player.html')).href);await p.locator('#playerStart:not([disabled])').click();if(id==='game')await p.locator('#formSurface .component[data-id="star"]').click();await p.waitForFunction(()=>document.querySelector('#formSurface')?.textContent.includes('お手本の改造保存'),null,{timeout:25000});assert.ok(await p.locator('#formSurface img').evaluateAll(imgs=>imgs.length>0&&imgs.every(i=>i.complete&&i.naturalWidth>0)));await p.locator('#playerStop').click();}finally{await context.close();}
  }
 });
 await test('SAMPLES-LOCKS',async page=>{await page.locator('#uiLevel').selectOption('advanced');await open(page,'game');await page.locator('#runBtn').click();await page.waitForFunction(()=>Akari.app.editorState.state==='RUNNING');for(const control of ['sampleBtn','sampleSelect','sampleHelpBtn'])assert.equal(await page.locator('#'+control).isDisabled(),true);await page.locator('#pauseBtn').click();await page.waitForFunction(()=>Akari.app.editorState.state==='PAUSED');for(const control of ['sampleBtn','sampleSelect'])assert.equal(await page.locator('#'+control).isDisabled(),true);await page.locator('#stopBtn').click();assert.equal(await page.locator('#sampleBtn').isEnabled(),true);});
 await test('SAMPLES-RESPONSIVE-HINTS',async page=>{
  for(const width of [1366,390])for(const level of ['basic','advanced'])for(const mode of ['code','blocks']){await page.setViewportSize({width,height:900});await page.locator('#uiLevel').selectOption(level);await page.locator('#editorMode'+mode).click();for(const id of samplesFeature.ids){await page.locator('#sampleSelect').selectOption(id);await page.locator('#sampleHelpBtn').click();assert.equal(await page.locator('#sampleHelpRows tr').count(),6);assert.match(await page.locator('#sampleHelpRows').innerText(),/交換する/);assert.match(await page.locator('#sampleHelpRows').innerText(),/並べ替える/);const bounds=await page.locator('#sampleHelp').boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=width);await page.locator('#sampleHelpClose').click();}await page.locator('#sampleBtn').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#sampleConfirm').evaluate(e=>e.open),true);await page.keyboard.press('Escape');assert.equal(await page.locator('#sampleConfirm').evaluate(e=>e.open),false);}
  const ctx=await browser.newContext({offline:true,hasTouch:true,viewport:{width:390,height:844}}),p=await ctx.newPage();p.on('pageerror',e=>report.pageErrors.push(e.message));try{await p.goto(pathToFileURL(path.resolve(product)).href);await p.waitForFunction(()=>!!Akari.app);await p.locator('#sampleBtn').tap();await p.locator('#sampleConfirmYes').tap();assert.equal(await p.evaluate(()=>Akari.app.project.name),samplesFeature.names[0]);}finally{await ctx.close();}
 });
},420000);}catch(e){report.hostFailure=e.stack;console.error(e.stack);}
for(const id of sampleTestIds)if(!report.results.some(r=>r.id===id))report.results.push({id,status:'FAIL',error:'Required check did not execute'});
const artifactNames=['dance.png','flower.png','game.png',...samplesFeature.ids.flatMap(id=>[id+'.akari.md',id+'-player.html'])];report.artifacts=artifactNames.filter(n=>fs.existsSync(path.join(dir,n))).map(n=>({path:n,sha256:sha(fs.readFileSync(path.join(dir,n)))}));
report.status=!report.hostFailure&&!report.pageErrors.length&&!report.networkRequests.length&&report.results.every(r=>r.status==='PASS')?'PASS':'FAIL';
if(report.status==='PASS'){try{verifySamples(report,inputs,dir);}catch(e){report.status='FAIL';report.hostFailure=e.stack;console.error(e.stack);}}
save();if(report.status!=='PASS')process.exitCode=1;
