const L=require('./audit-lib.cjs'),assert=require('assert/strict'),{pathToFileURL}=require('url');
const{chromium}=require('playwright');
(async()=>{const dir=L.path.resolve(process.argv[2]||'audit-evidence/browser/candidate'),manifest=L.verifyManifest(dir),results=[],errors=[],network=[],b=await chromium.launch({executablePath:(process.env.AKARI_BROWSER||undefined),headless:true,args:['--allow-file-access-from-files']}),url=pathToFileURL(L.path.join(dir,manifest.candidate)).href;
const run=async(id,fn)=>{const c=await b.newContext({viewport:{width:1440,height:900}});await c.route(/^https?:\/\//,r=>{network.push(r.request().url());return r.abort();});await c.addInitScript(()=>{const real=Crypto.prototype.getRandomValues;Crypto.prototype.getRandomValues=function(array){if(array instanceof Uint32Array&&array.length===1){array[0]=12345;return array;}return real.call(this,array);};window.__decodeDelay=0;window.__decodeReject=false;const decode=AudioContext.prototype.decodeAudioData;AudioContext.prototype.decodeAudioData=function(...args){return new Promise((resolve,reject)=>setTimeout(()=>__decodeReject?reject(new Error('audit decode failure')):decode.apply(this,args).then(resolve,reject),__decodeDelay));};});const p=await c.newPage();p.setDefaultTimeout(15000);p.on('pageerror',e=>errors.push({id,error:e.message}));p.on('dialog',d=>d.accept(d.type()==='prompt'?d.defaultValue():undefined));try{await p.goto(url);results.push({id,pass:true,evidence:await fn(p)});console.log('PASS '+id);}catch(e){results.push({id,pass:false,error:e.message.split('\n').slice(0,12).join('\n')});console.log('FAIL '+id+': '+e.message.split('\n')[0]);await p.screenshot({path:L.path.join(dir,id+'.png'),fullPage:true}).catch(()=>{});}finally{await c.close();L.result(L.path.join(dir,'browser-runtime.json'),{manifest,browser:b.version(),results,pageErrors:errors,networkRequests:network});}};
const state=p=>p.evaluate(()=>{const a=Akari.app,s=a.editorState;return{source:s.main.sourceText,project:JSON.stringify(a.project),history:s.history,redo:s.redo,dirty:s.dirty,mode:s.main.mode,state:s.state};});const waitForConsoleAppend=async(p,before,needle)=>p.waitForFunction(({before,needle})=>{const text=document.querySelector('#console')?.textContent||'';const count=(value,part)=>part?value.split(part).length-1:0;return count(text,needle)>count(before||'',needle);},{before,needle});const fill=async(p,text)=>{await (await reveal09(p.locator('#codeEditor'))).fill(text);await p.waitForTimeout(350);};const list=async p=>{const row=p.locator('#runtimeMonitor .monitor-row').filter({has:p.locator('.monitor-key',{hasText:/^名前一覧$/})});await (await reveal09(row.locator('button'))).click();const n=Number(await p.locator('#valueItem').getAttribute('max')),values=[];for(let i=0;i<n;i++){values.push(await p.locator('#valueOutput').textContent());if(i+1<n)await (await reveal09(p.locator('#valueItemNext'))).click();}await (await reveal09(p.locator('#valueClose'))).click();return values;};
try{
await run('runtime-fixed-seed-mode-switch-trace',async p=>{const source='名前一覧を空にする。\n次のことを5回くり返す。\n  名前一覧に乱数（1、100000）を追加する。\n  0.2秒待つ。\n「乱数完了」と言う。';await fill(p,source);const traces=[];for(const mode of ['code','blocks']){await p.locator('#editorMode'+mode).click();const before=await state(p),consoleBefore=await p.locator('#console').textContent();await (await reveal09(p.locator('#runBtn'))).click();await p.waitForFunction(()=>Akari.app.editorState.state==='RUNNING');await p.waitForTimeout(100);await (await reveal09(p.locator('#pauseBtn'))).click();assert.equal((await state(p)).state,'PAUSED');const seed=await p.locator('#runtimeMonitor .monitor-row').filter({has:p.locator('.monitor-key',{hasText:/^乱数種$/})}).locator('.monitor-value').textContent();assert.equal(seed,'12345');await p.locator('#editorMode'+(mode==='code'?'blocks':'code')).click();await p.setViewportSize({width:320,height:568});await p.setViewportSize({width:1440,height:900});assert.equal((await state(p)).state,'PAUSED');assert.equal((await state(p)).project,before.project);await (await reveal09(p.locator('#stepBtn'))).click();assert.equal((await state(p)).state,'PAUSED');await (await reveal09(p.locator('#continueBtn'))).click();await waitForConsoleAppend(p,consoleBefore,'乱数完了');await p.waitForTimeout(1200);traces.push({initialMode:mode,seed,values:await list(p)});await (await reveal09(p.locator('#stopBtn'))).click();assert.equal((await state(p)).project,before.project);assert.equal((await state(p)).source,source);}assert.equal(traces[0].values.length,5);assert.deepEqual(traces[0].values,traces[1].values);return{traces,pauseResizeSwitchStepResumeNoReset:true};});
await run('preparing-importing-lock-and-decode-failure-rollback',async p=>{await fill(p,'「tone」を鳴らし、終わるまで待つ。\n「音完了」と言う。');await (await reveal09(p.locator('#editorModeblocks'))).click();await p.evaluate(()=>__decodeDelay=700);const before=await state(p);await (await reveal09(p.locator('#assetBtn'))).click();await p.locator('#soundInput').setInputFiles(L.path.join(__dirname,'media','tone.wav'));await p.waitForFunction(()=>Akari.app.editorState.state==='IMPORTING');assert.equal(await p.locator('#editorModecode').isDisabled(),true);assert.equal(await p.locator('#runBtn').isDisabled(),true);assert.equal((await state(p)).project,before.project);await p.waitForFunction(()=>Akari.app.project.sounds.length===1&&Akari.app.editorState.state==='DESIGN');await (await reveal09(p.locator('#assetClose'))).click();const loaded=await state(p);await (await reveal09(p.locator('#runBtn'))).click();await p.waitForFunction(()=>Akari.app.editorState.state==='PREPARING');assert.equal(await p.locator('#editorModecode').isDisabled(),true);assert.equal(await p.locator('#undoBtn').isDisabled(),true);assert.equal(await p.locator('#blockEditor [data-blockui-field]').first().isDisabled(),true);await (await reveal09(p.locator('#stopBtn'))).click();assert.equal((await state(p)).state,'DESIGN');await p.waitForTimeout(900);assert.equal((await state(p)).state,'DESIGN');assert.equal((await state(p)).project,loaded.project);await p.evaluate(()=>{__decodeDelay=100;__decodeReject=true;});await (await reveal09(p.locator('#runBtn'))).click();await p.waitForFunction(()=>Akari.app.editorState.state==='DESIGN');assert.equal((await state(p)).project,loaded.project);assert.equal((await state(p)).source,loaded.source);assert.ok((await p.locator('#console').textContent()).includes('準備失敗'));await p.evaluate(()=>__decodeReject=false);const retryConsole=await p.locator('#console').textContent();await (await reveal09(p.locator('#runBtn'))).click();await waitForConsoleAppend(p,retryConsole,'音完了');await (await reveal09(p.locator('#stopBtn'))).click();return{importingAndPreparingSwitchDisabled:true,latePrepareCannotResurrect:true,decodeFailureRetainsProjectAndSource:true,retryRealDecodeRun:true};});
await run('question-answer-and-question-stop-both-modes',async p=>{const source='「答えは？」とたずねる。\n答えと言う。';await fill(p,source);const evidence=[];for(const mode of ['code','blocks']){await p.locator('#editorMode'+mode).click();await (await reveal09(p.locator('#runBtn'))).click();await p.locator('#questionModal.show').waitFor();await (await reveal09(p.locator('#questionAnswer'))).fill('返答'+mode);const answerConsole=await p.locator('#console').textContent();await (await reveal09(p.locator('#questionSubmit'))).click();await waitForConsoleAppend(p,answerConsole,'返答'+mode);await (await reveal09(p.locator('#stopBtn'))).click();await (await reveal09(p.locator('#runBtn'))).click();await p.locator('#questionModal.show').waitFor();await (await reveal09(p.locator('#questionStop'))).click();assert.equal((await state(p)).state,'DESIGN');assert.equal((await state(p)).source,source);await (await reveal09(p.locator('#runBtn'))).click();await p.locator('#questionModal.show').waitFor();await p.keyboard.press('Escape');assert.equal((await state(p)).state,'DESIGN');evidence.push({mode,answerObserved:true,questionStop:true,escapeStop:true});}return evidence;});
}finally{await b.close();}console.log(JSON.stringify({passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass).length,errors,network}));if(results.some(r=>!r.pass)||errors.length||network.length)process.exitCode=1;
})().catch(e=>{console.error(e.message);process.exitCode=1;});


async function reveal09(locator){
 if(await locator.count()===1){if(!await locator.isVisible())for(const panel of await locator.locator('xpath=ancestor::*[contains(concat(" ",normalize-space(@class)," ")," blockui-side-folded ")]').all())await panel.locator('.blockui-side-toggle').click();const ancestors=locator.locator(await locator.evaluate(e=>e.tagName==='SUMMARY')?'xpath=parent::details/ancestor::details[not(@open)]':'xpath=ancestor::details[not(@open)]');for(const detail of await ancestors.all())await detail.locator(':scope > summary').click();}
 return locator;
}
