const U=require('./ui-routes.cjs');
const L=require('./audit-lib.cjs'),assert=require('assert/strict'),{pathToFileURL}=require('url');
const{chromium}=require('playwright');
(async()=>{const dir=L.path.resolve(process.argv[2]||'audit-evidence/browser/candidate'),manifest=L.verifyManifest(dir),filter=process.argv[3]?.split(','),api=L.loadApi(L.read(L.path.join(dir,manifest.candidate))),schemas=JSON.parse(JSON.stringify(api.BLOCK_SCHEMAS)),results=[],errors=[],network=[],browser=await chromium.launch({executablePath:(process.env.AKARI_BROWSER||undefined),headless:true,args:['--allow-file-access-from-files']});
const context=await browser.newContext({viewport:{width:1440,height:900},acceptDownloads:true});await context.route(/^https?:\/\//,r=>{network.push(r.request().url());return r.abort();});const p=await context.newPage();p.setDefaultTimeout(8000);p.on('pageerror',e=>errors.push(e.stack));p.on('dialog',d=>d.accept(d.type()==='prompt'?d.defaultValue():undefined));await p.goto(pathToFileURL(L.path.join(dir,manifest.candidate)).href);await (await reveal09(p.locator('#assetBtn'))).click();await p.locator('#soundInput').setInputFiles(L.path.join(__dirname,'media','tone.wav'));await p.waitForFunction(()=>Akari.app.project.sounds.length===1);await (await reveal09(p.locator('#assetClose'))).click();await (await reveal09(p.locator('.tool[data-type="input"]'))).click();let inputId=await p.locator('#objectSelect').inputValue();let draft=false,rootId='#blockEditor';
const session=()=>p.evaluate(d=>(d?Akari.app.editorState.draft:Akari.app.editorState.main),draft);
const mode=async which=>{await p.locator(`#${draft?'callable':'editor'}Mode${which}`).click();await p.locator(rootId).waitFor({state:which==='blocks'?'visible':'hidden'});};
const root=()=>p.locator(rootId),node=(id)=>root().locator('.blockui-node[data-block-id="'+id+'"]');
const locate=async schema=>{const s=await session(),found=[];const walk=n=>{if(n.schemaId===schema)found.push(n);for(const v of Object.values(n.inputs||{}))(Array.isArray(v)?v:[v]).forEach(walk);for(const v of Object.values(n.bodies||{}))v.forEach(walk);};walk(s.blockView);return found;};
const add=async schema=>{await (await reveal09(root().locator('[data-blockui-search]'))).fill(schema);const button=root().locator('[data-blockui-schema="'+schema+'"]');assert.equal(await button.count(),1,'palette '+schema);if(await button.isDisabled())throw Error('Disabled palette '+schema+': '+await button.getAttribute('title'));await button.click();};
const reset=async s=>{if(await p.locator('#procModal').isVisible())await (await reveal09(p.locator('#procClose'))).click();draft=['ReturnStatement','LocalVariableDeclaration','LocalListDeclaration'].includes(s.id);rootId=draft?'#callableBlocks':'#blockEditor';if(draft){await (await reveal09(p.locator('#procBtn'))).click();await p.locator(s.id==='ReturnStatement'?'#callableNewFunction':'#callableNewAction').click();await (await reveal09(p.locator('#callableName'))).fill('検証定義');await mode('code');await (await reveal09(p.locator('#callableCode'))).fill('');}else{await (await reveal09(p.locator('#objectSelect'))).selectOption(s.id==='SensorRead:以前の値'||s.id==='SensorRead:新しい値'?inputId:s.id==='LooksCommand:SET_SELF_TEXT'?'button-1':'sprite-1');let event=s.id==='CloneCommand:DELETE_SELF'?'cloneStart':'start';if(s.id==='SensorRead:以前の値'||s.id==='SensorRead:新しい値')event='valueChanged';if(s.id==='SensorRead:受け取った知らせ')event='message';if(s.id==='SensorRead:押されたキー')event='keyDown';if(s.id==='SensorRead:以前の背景名'||s.id==='SensorRead:新しい背景名')event='backdropChanged';const available=await p.locator('#eventSelect option').evaluateAll(o=>o.map(x=>x.value));if(available.includes(event))await (await reveal09(p.locator('#eventSelect'))).selectOption(event);await mode('code');await (await reveal09(p.locator('#codeEditor'))).fill('');}await mode('blocks');await (await reveal09(root().locator('[data-blockui-search]'))).fill('');await (await reveal09(root().locator('[data-blockui-palette-mode]'))).selectOption('statement');await root().locator('.blockui-palette-options > summary').click();};
const editField=async(id,f,annotation=false)=>{if(f.key==='hasElse')await U.openNodeMenu(node(id));if(annotation)await U.openAnnotations(node(id));let control=root().locator('['+(annotation?'data-blockui-annotation':'data-blockui-field')+'="'+f.key+'"][data-block-id="'+id+'"]');if(annotation){const details=control.locator('xpath=ancestor::details');if(!(await details.getAttribute('open')!==null))await (await reveal09(details.locator('summary'))).click();}const before=await control.inputValue();let value;
 if(f.type==='boolean'){value=before==='true'?'false':'true';await (await reveal09(control)).selectOption(value);}else if(f.type==='qualifier'){value=before==='project'?'exact':'project';await (await reveal09(control)).selectOption(value);}else{value=annotation?(f.fixtureValue||'※ 注釈  '):f.type==='number'?'13':f.type==='comment'?' コメント改　 ':f.type==='string'?'文字改':f.key==='binder'?'要素改':'名前改';await (await reveal09(control)).fill(value);await control.press('Tab');}
 const active=await session();assert.equal(active.pendingEdit,null,`${id}.${f.key} pending`);assert.notEqual(value,before);return{key:f.key,type:f.type,before,value,annotation};};
const action=(id,name)=>({click:async()=>{await U.openNodeMenu(node(id));await node(id).locator(':scope > .blockui-node-head [data-blockui-action="'+name+'"]').click();}});
const bodyPosition=(id,body,position)=>({click:async()=>keyboardActivate09(root().locator('[data-blockui-action="body-insert"][data-parent-id="'+id+'"][data-blockui-body="'+body+'"][data-insert-index="'+position+'"]'))});
const slot=(id,input)=>({click:async()=>selectSlot09(root().locator('[data-parent-id="'+id+'"][data-blockui-input="'+input+'"]').first())});
const append=async(schema)=>{const state=await session(),r=state.blockView,position=state.context.definitionKind==='function'&&r.bodies.body.at(-1)?.schemaId==='ReturnStatement'?r.bodies.body.length-1:r.bodies.body.length;await bodyPosition(r.id,'body',position).click();await add(schema);return(await session()).blockView.bodies.body[position];};
const historyRoundtrip=async before=>{const after=await session();assert.notEqual(after.sourceText,before.sourceText,'operation changes source');await p.keyboard.press('Control+z');assert.equal((await session()).sourceText,before.sourceText,'undo exact source');await p.keyboard.press('Control+y');assert.equal((await session()).sourceText,after.sourceText,'redo exact source');};
const structuralOperations=async(s,id)=>{
 if(s.category==='expression'){
  const original=(await locate(s.id))[0],destination=await append('Say');await slot(destination.id,'value').click();await add('BinaryExpression:ADD');const nested=(await session()).blockView.bodies.body.at(-1).inputs.value;
  await action(original.id,'duplicate').click();await slot(nested.id,'left').click();let now=await session(),copied=now.blockView.bodies.body.at(-1).inputs.value.inputs.left;assert.equal(copied.schemaId,s.id);assert.equal(api.astEquivalent(api.blockDecode(now.blockView),api.parseSyntax(now.sourceText,now.context).ast),true,'tree decode agrees after copy');
  await action(copied.id,'move').click();await slot(nested.id,'right').click();await (await reveal09(root().locator('[data-blockui-replacement-schema]'))).selectOption('NumberLiteral');await (await reveal09(root().locator('[data-blockui-action="confirm-expression-move"]'))).click();now=await session();assert.equal(now.blockView.bodies.body.at(-1).inputs.value.inputs.right.schemaId,s.id);assert.equal(now.blockView.bodies.body.at(-1).inputs.value.inputs.left.schemaId,'NumberLiteral');
  const before=await session();await action(destination.id,'remove').click();await historyRoundtrip(before);return{duplicateIntoNestedSlot:true,movedAcrossRequiredSlotsWithReplacement:true,deleteContainingStatement:true,undoRedoExact:true};
 }
 let current=await session(),originalId=s.category==='target'?current.blockView.bodies.body[0].id:s.category==='script'?current.blockView.bodies.body[0].id:id;
 const container=await append('RepeatCount');await editField(container.bodies.body[0].id,{key:'inlineComment',fixtureValue:'※ 移動先 '},true);await action(originalId,'duplicate').click();current=await session();const list=[];const walk=n=>{list.push(n);for(const children of Object.values(n.bodies||{}))children.forEach(walk);};walk(current.blockView);const original=list.find(n=>n.id===originalId),copy=list.filter(n=>n.schemaId===original.schemaId&&n.id!==originalId&&n.id!==container.id).find(n=>JSON.stringify({...n,id:null})===JSON.stringify({...original,id:null}))||list.find(n=>n.schemaId===original.schemaId&&n.id!==originalId&&n.id!==container.id);
 assert.ok(copy,'duplicate present');await action(copy.id,'move').click();await bodyPosition(container.id,'body',1).click();current=await session();const moved=current.blockView.bodies.body.find(n=>n.id===container.id).bodies.body;assert.equal(moved.at(-1).id,copy.id);await action(copy.id,'move-up').click();await action(copy.id,'move-down').click();const before=await session();await action(copy.id,'remove').click();await historyRoundtrip(before);return{scope:s.category==='target'?'required target through owning statement':s.category==='script'?'root body child':'statement',duplicate:true,nestedMove:true,reorderBothDirections:true,delete:true,undoRedoExact:true};
};
const saveReopen=async(index)=>{
 const before=await session(),owner=before.ownerKey;
 if(draft){await (await reveal09(p.locator('#callableName'))).fill('保存検査'+index);await (await reveal09(p.locator('#callableSave'))).click();assert.equal(await p.evaluate(()=>Akari.app.editorState.hasDraft),false);}
 const definition=draft?await p.evaluate(()=>Akari.app.editorState.callableDraft.loadedKey):null;if(draft)await (await reveal09(p.locator('#procClose'))).click();
 const expected=await p.evaluate(()=>JSON.stringify(Akari.app.project)),downloadPromise=p.waitForEvent('download');await (await reveal09(p.locator('#saveBtn'))).click();const download=await downloadPromise,file=L.path.join(dir,'schema-roundtrip-'+index+'.akari.md');await download.saveAs(file);await (await reveal09(p.locator('#newBtn'))).click();assert.notEqual(await p.evaluate(()=>JSON.stringify(Akari.app.project)),expected);await p.locator('#fileInput').setInputFiles(file);await p.waitForFunction(expected=>JSON.stringify(Akari.app.project)===expected,expected);
 if(draft){await (await reveal09(p.locator('#procBtn'))).click();await (await reveal09(p.locator('#callableSelect'))).selectOption(definition);}else{const[,id,event]=owner.split(':');await (await reveal09(p.locator('#objectSelect'))).selectOption(id);await (await reveal09(p.locator('#eventSelect'))).selectOption(event);}
 await mode('blocks');const after=await session();assert.equal(after.sourceText,before.sourceText,'saved source exact');assert.equal(api.astEquivalent(before.syntaxAst,after.syntaxAst),true,'saved AST/comments exact');return{file:L.path.basename(file),bytes:L.fs.statSync(file).size,explicitDraftSave:draft,sourceExact:true,astAndCommentEquivalent:true};
};
try{for(const s of schemas){if(filter&&!filter.includes(s.id))continue;const evidence={category:s.category,fields:[],inputs:[],bodies:[],annotations:[]};try{await reset(s);let id;if(s.id==='Script'){id=(await session()).blockView.id;await add('NoOperation');evidence.creation='Implicit root with palette-created body';}else if(s.category==='target'){await add('Assignment');id=(await locate(s.id))[0].id;evidence.creation='Assignment target slot';}else if(s.category==='expression'){await add('Say');const say=(await locate('Say'))[0];await selectSlot09(root().locator('[data-blockui-input="value"][data-parent-id="'+say.id+'"]').first());await add(s.id);id=(await locate(s.id))[0].id;evidence.creation='Expression palette into Say.value';}else{if(['Break','Continue'].includes(s.id)){await add('Forever');const owner=(await locate('Forever'))[0];await root().locator('[data-blockui-body="body"][data-parent-id="'+owner.id+'"]').last().click();}await add(s.id);id=(await locate(s.id))[0].id;evidence.creation='Statement palette';}
 assert.ok(await node(id).count()||s.id==='Script','Created node visible '+s.id);
 for(const f of s.fields){evidence.fields.push(await editField(id,f));id=(await locate(s.id))[0].id;}
 for(const a of s.annotations.filter(x=>x.editable!==false)){if(a.key==='elseComment'&&!(await locate(s.id))[0].fields.hasElse)continue;evidence.annotations.push(await editField(id,a,true));}
 // Edit every declared value slot through its own child controls, including fixed arity arguments.
 for(const input of s.inputs){let created=(await locate(s.id))[0],children=input.multiple?created.inputs[input.key]:[created.inputs[input.key]];const slotResult={key:input.key,multiple:input.multiple,count:children.length,edited:[]};for(let i=0;i<children.length;i++){const child=children[i],childSchema=schemas.find(x=>x.id===child.schemaId);for(const f of childSchema.fields){slotResult.edited.push({index:i,schema:child.schemaId,...await editField(child.id,f)});}if(!childSchema.fields.length&&input.type==='expression'){const slot=root().locator('[data-blockui-input="'+input.key+'"][data-parent-id="'+id+'"]'+(input.multiple?'[data-slot-index="'+i+'"]':''));await selectSlot09(slot.first());await add('NumberLiteral');slotResult.edited.push({index:i,replacedBy:'NumberLiteral'});}}
 if(input.variadic){const before=children.length;await node(id).locator('[data-blockui-action="variadic-add"]').first().click();created=(await locate(s.id))[0];assert.equal(created.inputs[input.key].length,before+1);slotResult.variadicAdded=true;}
 evidence.inputs.push(slotResult);}
 for(const body of s.bodies){const owner=(await locate(s.id))[0];if(body.when&&!owner.fields[body.when])continue;const before=owner.bodies[body.key].length;await root().locator('[data-blockui-body="'+body.key+'"][data-parent-id="'+id+'"]').last().click();await add('NoOperation');assert.equal((await locate(s.id))[0].bodies[body.key].length,before+1);evidence.bodies.push({key:body.key,insertedNoOperation:true});}
 evidence.structuralOperations=await structuralOperations(s,id);const before=await session();assert.equal(before.pendingEdit,null);assert.ok(before.syntaxAst);const equivalent=await p.evaluate(d=>{const A=Akari,s=d?A.app.editorState.draft:A.app.editorState.main;const parsed=A.parseSyntax(s.sourceText,s.context);return !!parsed.ast&&A.astEquivalent(s.syntaxAst,parsed.ast)&&A.astEquivalent(A.blockDecode(s.blockView),parsed.ast);},draft);assert.equal(equivalent,true,'block/source AST');await mode('code');const text=await p.locator(draft?'#callableCode':'#codeEditor').inputValue();assert.equal(text,before.sourceText);await mode('blocks');assert.equal((await session()).sourceText,text);evidence.source=text;evidence.diagnostics=before.diagnostics;evidence.roundtrip=true;evidence.saveReopen=await saveReopen(schemas.indexOf(s));results.push({id:s.id,pass:true,evidence});console.log('PASS '+s.id);
 }catch(e){results.push({id:s.id,pass:false,evidence,error:e.message.split('\n').slice(0,9).join('\n')});console.log('FAIL '+s.id+': '+e.stack);L.result(L.path.join(dir,'schema-debug.json'),results);await p.screenshot({path:L.path.join(dir,'schema-failure-'+results.length+'.png'),fullPage:true}).catch(()=>{});await p.goto(pathToFileURL(L.path.join(dir,manifest.candidate)).href);await p.waitForTimeout(350);await (await reveal09(p.locator('#assetBtn'))).click();await p.locator('#soundInput').setInputFiles(L.path.join(__dirname,'media','tone.wav'));await p.waitForFunction(()=>Akari.app.project.sounds.length>=1);await (await reveal09(p.locator('#assetClose'))).click();await (await reveal09(p.locator('.tool[data-type="input"]'))).click();inputId=await p.locator('#objectSelect').inputValue();}
 L.result(L.path.join(dir,'schema-case-'+schemas.indexOf(s)+'.json'),results.at(-1));}
L.result(L.path.join(dir,filter?'browser-schemas-selected.json':'browser-schemas.json'),{manifest,browser:browser.version(),expected:schemas.length,results,pageErrors:errors,networkRequests:network});
}finally{await browser.close();}console.log(JSON.stringify({passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass).length,pageErrors:errors,networkRequests:network}));if(results.some(r=>!r.pass)||errors.length||network.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});


async function reveal09(locator){
 if(await locator.count()===1){if(!await locator.isVisible())for(const panel of await locator.locator('xpath=ancestor::*[contains(concat(" ",normalize-space(@class)," ")," blockui-side-folded ")]').all())await panel.locator('.blockui-side-toggle').click();const ancestors=locator.locator(await locator.evaluate(e=>e.tagName==='SUMMARY')?'xpath=parent::details/ancestor::details[not(@open)]':'xpath=ancestor::details[not(@open)]');for(const detail of await ancestors.all())await detail.locator(':scope > summary').click();}
 return locator;
}

async function keyboardActivate09(l){const p=l.page();for(let i=0;i<500&&!await l.evaluate(e=>e===document.activeElement);i++){const backwards=await l.evaluate(e=>!!(e.compareDocumentPosition(document.activeElement)&Node.DOCUMENT_POSITION_FOLLOWING));await p.keyboard.press(backwards?'Shift+Tab':'Tab');}assert(await l.evaluate(e=>e===document.activeElement),'exact insertion receives keyboard focus');await l.press('Enter');}
async function selectSlot09(slot){await U.clickNode(slot.locator(':scope > .blockui-node'));await U.openSlot(slot);return keyboardActivate09(slot.locator(':scope > .blockui-slot-head [data-blockui-action="slot-select"]'));}
