const L=require('./audit-lib.cjs'),assert=require('assert/strict'),{pathToFileURL}=require('url');
const{chromium}=require('playwright');
(async()=>{const dir=L.path.resolve(process.argv[2]||'audit-evidence/browser/candidate'),manifest=L.verifyManifest(dir),results=[],errors=[],network=[],b=await chromium.launch({executablePath:(process.env.AKARI_BROWSER||undefined),headless:true,args:['--allow-file-access-from-files']});const c=await b.newContext({viewport:{width:1440,height:900}});await c.route(/^https?:\/\//,r=>{network.push(r.request().url());return r.abort();});const p=await c.newPage();p.setDefaultTimeout(15000);p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept(d.type()==='prompt'?d.defaultValue():undefined));try{await p.goto(pathToFileURL(L.path.join(dir,manifest.candidate)).href);
 const defaultSpriteName=await p.evaluate(()=>Akari.app.project.components.find(x=>x.id==='sprite-1').name);const objects=[{id:'stage',type:'stage'},{id:'button-1',type:'button'},{id:'sprite-1',type:'sprite'}];for(const[type,x,y]of [['label',30,120],['box',470,50],['input',360,300]]){await p.locator('.tool[data-type="'+type+'"]').click();const id=await p.locator('#objectSelect').inputValue(),node=p.locator('.component[data-id="'+id+'"]');await node.scrollIntoViewIfNeeded();const rect=await node.boundingBox(),stage=await p.locator('#formSurface').boundingBox(),scale=stage.width/640;await p.mouse.move(rect.x+rect.width/2,rect.y+rect.height/2);await p.mouse.down();await p.mouse.move(stage.x+x*scale+rect.width/2,stage.y+y*scale+rect.height/2,{steps:5});await p.mouse.up();objects.push({id,type});}
 await (await reveal09(p.locator('#assetBtn'))).click();await (await reveal09(p.locator('#backdropName'))).fill('第二背景');await (await reveal09(p.locator('#backdropColor'))).fill('#ffffff');await (await reveal09(p.locator('#backdropAdd'))).click();await (await reveal09(p.locator('#assetClose'))).click();const events=await p.evaluate(()=>Akari.EVENT_BY_TYPE),expected=[];
 for(const object of objects){await (await reveal09(p.locator('#objectSelect'))).selectOption(object.id);for(const event of events[object.type]){await (await reveal09(p.locator('#eventSelect'))).selectOption(event);await (await reveal09(p.locator('#editorModecode'))).click();const tag=object.type+':'+event;expected.push(tag);let source='名前一覧に「'+tag+'」を追加する。';if(object.type==='stage'&&event==='start')source='名前一覧を空にする。\n'+source;if(object.type==='button'&&event==='click')source+='\n「検査」と知らせ、受け手の処理が終わるまで待つ。\n次の背景にする。\n「'+defaultSpriteName+'」のクローンを作る。';if(event==='cloneStart')source+='\nこのクローンを削除する。';await (await reveal09(p.locator('#codeEditor'))).fill(source);await (await reveal09(p.locator('#editorModeblocks'))).click();assert.ok(await p.locator('#blockEditor .blockui-node').count());assert.equal(await p.evaluate(()=>Akari.app.editorState.main.sourceText),source);results.push({id:'event:'+object.type+':'+event,source,selectionAndBlockView:true});}}
 assert.equal(expected.length,32);assert.deepEqual(await p.evaluate(()=>Akari.app.compile().errors),[]);const projectBefore=await p.evaluate(()=>JSON.stringify(Akari.app.project));await (await reveal09(p.locator('#runBtn'))).click();await p.waitForFunction(()=>Akari.app.editorState.state==='RUNNING');await p.waitForTimeout(200);
 const form=p.locator('#formSurface');await form.scrollIntoViewIfNeeded();const displayed=await form.boundingBox(),logical=await p.evaluate(()=>({width:Akari.app.project.stage.width,height:Akari.app.project.stage.height}));assert.ok(displayed.width>0&&displayed.height>0);
 await form.click({position:{x:15*displayed.width/logical.width,y:360*displayed.height/logical.height}});for(const obj of objects.filter(x=>x.type!=='stage')){await p.locator('.component[data-runtime-id="'+obj.id+'"]').click();}await form.focus();await p.keyboard.press('a');await p.locator('.component[data-runtime-id="'+objects.find(x=>x.type==='input').id+'"]').fill('入力更新');await p.waitForTimeout(450);
 const row=p.locator('#runtimeMonitor .monitor-row').filter({has:p.locator('.monitor-key',{hasText:/^名前一覧$/})});await (await reveal09(row.locator('button'))).click();const count=Number(await p.locator('#valueItem').getAttribute('max')),observed=[];for(let i=0;i<count;i++){observed.push(await p.locator('#valueOutput').textContent());if(i+1<count)await (await reveal09(p.locator('#valueItemNext'))).click();}await (await reveal09(p.locator('#valueClose'))).click();for(const tag of expected)assert.ok(observed.includes(tag),'Runtime event missing '+tag+' in '+JSON.stringify(observed));assert.equal(new Set(observed.filter(x=>expected.includes(x))).size,32);await (await reveal09(p.locator('#stopBtn'))).click();assert.equal(await p.evaluate(()=>JSON.stringify(Akari.app.project)),projectBefore);for(const r of results){r.runtimeObserved=true;r.pass=true;}L.result(L.path.join(dir,'browser-events.json'),{manifest,browser:b.version(),results,expected,observed,pageErrors:errors,networkRequests:network});console.log(JSON.stringify({passed:results.length,observed:observed.length,errors,network}));
 }catch(e){L.result(L.path.join(dir,'browser-events.json'),{manifest,results,error:e.message,pageErrors:errors,networkRequests:network});console.error(e.message);await p.screenshot({path:L.path.join(dir,'events-failure.png'),fullPage:true}).catch(()=>{});process.exitCode=1;}finally{await b.close();}})();


async function reveal09(locator){
 if(await locator.count()===1){if(!await locator.isVisible())for(const panel of await locator.locator('xpath=ancestor::*[contains(concat(" ",normalize-space(@class)," ")," blockui-side-folded ")]').all())await panel.locator('.blockui-side-toggle').click();const ancestors=locator.locator(await locator.evaluate(e=>e.tagName==='SUMMARY')?'xpath=parent::details/ancestor::details[not(@open)]':'xpath=ancestor::details[not(@open)]');for(const detail of await ancestors.all())await detail.locator(':scope > summary').click();}
 return locator;
}
