const {installStorageProbe,assertNoPersistence}=require('./persistence-probe.cjs');
const U=require('./ui-routes.cjs');
const L=require('./audit-lib.cjs'),assert=require('assert/strict'),{pathToFileURL}=require('url');
const {chromium}=require('playwright');
async function main(){
 const dir=L.path.resolve(process.argv[2]||L.path.join(__dirname,'candidate')),manifest=L.verifyManifest(dir),selected=process.argv[3]?.split(','),results=[],errors=[],network=[];
 const browser=await chromium.launch({executablePath:(process.env.AKARI_BROWSER||undefined),headless:true,args:['--allow-file-access-from-files']}),url=pathToFileURL(L.path.join(dir,manifest.candidate)).href;
 const run=async(id,fn)=>{if(selected&&!selected.includes(id))return;const context=await browser.newContext({viewport:{width:1440,height:900},acceptDownloads:true});await context.route(/^https?:\/\//,r=>{network.push(r.request().url());return r.abort();});const page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push({id,error:e.message}));page.on('dialog',d=>d.accept(d.type()==='prompt'?d.defaultValue():undefined));
  try{await page.goto(url);await page.waitForFunction(()=>!!globalThis.Akari?.app?.editorState);const evidence=await fn(page,context);results.push({id,pass:true,evidence});console.log('PASS '+id);}catch(e){results.push({id,pass:false,error:e.message.split('\n').slice(0,15).join('\n')});console.log('FAIL '+id+': '+e.message.split('\n')[0]);await page.screenshot({path:L.path.join(dir,id+'.png'),fullPage:true}).catch(()=>{});}finally{await context.close();L.result(L.path.join(dir,'browser-session.json'),{manifest,browser:browser.version(),results,pageErrors:errors,networkRequests:network});}};
 const state=p=>p.evaluate(()=>{const app=Akari.app,s=app.editorState,m=s.main,d=s.draft;return{project:JSON.stringify(app.project),main:{source:m?.sourceText,owner:m?.ownerKey,mode:m?.mode,revision:m?.sourceRevision,context:m?.contextRevision,diagnostics:m?.diagnostics,pending:m?.pendingEdit},draft:{source:d?.sourceText,owner:d?.ownerKey,mode:d?.mode},history:s.history,redo:s.redo,state:s.state,dirty:s.dirty,hasDraft:s.hasDraft,callableDraft:s.callableDraft};});
 const stable=s=>({project:s.project,source:s.main.source,owner:s.main.owner,history:s.history,redo:s.redo,dirty:s.dirty,hasDraft:s.hasDraft,callableDraft:s.callableDraft});
 const fill=async(p,text,selector='#codeEditor')=>{await p.locator(selector).fill(text);await p.waitForTimeout(350);};
 const mode=async(p,which,draft=false)=>{await p.locator(`#${draft?'callable':'editor'}Mode${which}`).click();await p.locator(draft?'#callableBlocks':'#blockEditor').waitFor({state:which==='blocks'?'visible':'hidden'});};
 const root=p=>p.locator('#blockEditor');
 const numeric=p=>root(p).locator('.blockui-node[data-schema-id="NumberLiteral"] [data-blockui-field="value"]').first();
 const blockEdit=async(p,value)=>{await numeric(p).fill(String(value));await numeric(p).press('Enter');};
 try{
  await run('crlf-no-edit-open-switch-save',async p=>{const file=L.path.join(dir,'crlf-fixture.akari.md'),text=await p.evaluate(()=>{const A=Akari,project=A.makeDefaultProject();project.scripts.find(x=>x.targetId==='stage'&&x.event==='start').source='※ CRLF  \r\n点数を1にする\r\n';project.functions=[{id:'function-crlf',name:'二倍',args:['値'],source:'※ 求値  \r\n値×2を返す\r\n'}];return A.serializeProject(project);});L.fs.writeFileSync(file,text);await p.locator('#fileInput').setInputFiles(file);await p.waitForFunction(()=>Akari.app.project.functions.length===1);const before=await state(p);assert.ok(before.main.source.includes('\r\n'));assert.ok(!(await p.locator('#codeEditor').inputValue()).includes('\r'));await mode(p,'blocks');await mode(p,'code');assert.deepEqual(stable(await state(p)),stable(before));await (await reveal09(p.locator('#procBtn'))).click();const callableBefore=(await state(p)).callableDraft.source;assert.ok(callableBefore.includes('\r\n'));await mode(p,'blocks',true);await mode(p,'code',true);assert.equal((await state(p)).callableDraft.source,callableBefore);await (await reveal09(p.locator('#procClose'))).click();const pending=p.waitForEvent('download');await (await reveal09(p.locator('#saveBtn'))).click();const download=await pending,output=L.path.join(dir,'crlf-saved.akari.md');await download.saveAs(output);const saved=await p.evaluate(t=>Akari.parseProjectFile(t).then(x=>x.project),L.read(output));assert.deepEqual(saved,JSON.parse(before.project));return{scriptAndFunctionCRLFExact:true,noEditSwitchKeepsHistoryDirty:true};});
  await run('switch-no-edit',async p=>{const raw='※ 先頭　 \n\n点数を 01 にする ※後ろ  \n次のことを2回くり返す\n  何もしない\n※末尾\t';await fill(p,raw);await p.locator('#codeEditor').evaluate(t=>t.setSelectionRange(4,17));const before=await state(p);assert.deepEqual(before.main.diagnostics,[]);for(let i=0;i<3;i++){await mode(p,'blocks');await mode(p,'code');}assert.equal(await p.locator('#codeEditor').inputValue(),raw);assert.deepEqual(stable(await state(p)),stable(before));assert.deepEqual(await p.locator('#codeEditor').evaluate(t=>[t.selectionStart,t.selectionEnd]),[4,17]);return{roundtrips:3,sourceSelectionHistoryDirtyExact:true};});
  await run('switch-semantic-errors',async p=>{const raw='未登録（1、2、3）を実行する\n不明な値と言う';await fill(p,raw);const before=await state(p);assert.ok(before.main.diagnostics.length);await mode(p,'blocks');assert.ok(await root(p).locator('.blockui-diagnostics').count());assert.equal(await root(p).locator('[data-blockui-field="name"]').first().inputValue(),'未登録');await mode(p,'code');assert.deepEqual(stable(await state(p)),stable(before));return{diagnostics:before.main.diagnostics,allNamesArgumentsRetained:true};});
  await run('switch-invalid-syntax',async p=>{await fill(p,'もし');const before=await state(p);assert.equal(await p.locator('#editorModeblocks').isDisabled(),true);assert.equal(await p.locator('#codeEditor').inputValue(),'もし');assert.deepEqual(stable(await state(p)),stable(before));return{switchDisabled:true,sourceRetained:true};});
  await run('block-edit-common-history',async p=>{await fill(p,'点数を1にする。');await fill(p,'点数を2にする。');await (await reveal09(p.locator('#undoBtn'))).click();const before=await state(p);assert.ok(before.redo>0);await mode(p,'blocks');await numeric(p).fill('1');await numeric(p).press('Enter');assert.deepEqual(stable(await state(p)),stable(before));await blockEdit(p,7);const changed=await state(p);assert.equal(changed.main.source,'点数を7にする。');assert.equal(changed.history,before.history+1);assert.equal(changed.redo,0);await (await reveal09(p.locator('#undoBtn'))).click();assert.equal((await state(p)).main.source,'点数を1にする。');await (await reveal09(p.locator('#redoBtn'))).click();assert.equal((await state(p)).main.source,'点数を7にする。');await mode(p,'code');await p.locator('#codeEditor').press('Control+z');assert.equal((await state(p)).main.source,'点数を1にする。');return{noOpPreservedRedo:true,guiAtomicHistory:true,keyboardUsesSharedHistory:true};});
  await run('pending-input-blocks-transitions',async p=>{await fill(p,'点数を1にする。');await mode(p,'blocks');const before=await state(p);await numeric(p).fill('-');for(const id of ['editorModecode','saveBtn','runBtn','exportBtn']){await p.locator('#'+id).click();assert.deepEqual(stable(await state(p)),stable(before),id);assert.equal((await state(p)).main.mode,'blocks');}await (await reveal09(p.locator('#eventSelect'))).selectOption('message');assert.equal(await p.locator('#eventSelect').inputValue(),'start');assert.deepEqual(stable(await state(p)),stable(before));await root(p).locator('[data-blockui-action="cancel"]').click();assert.equal(await numeric(p).inputValue(),'1');await mode(p,'code');return{transitionsRefused:['switch','save','run','export','event'],cancelRestoredInput:true};});
  await run('ime-code-and-block',async p=>{await fill(p,'点数を1にする。');const before=await state(p);await p.locator('#codeEditor').dispatchEvent('compositionstart');await p.locator('#codeEditor').evaluate(t=>{t.value='点数を2にする。';t.dispatchEvent(new InputEvent('input',{bubbles:true,isComposing:true,inputType:'insertCompositionText'}));});await (await reveal09(p.locator('#editorModeblocks'))).click();assert.equal((await state(p)).main.mode,'code');assert.deepEqual(stable(await state(p)),stable(before));await p.locator('#codeEditor').dispatchEvent('compositionend');await p.waitForTimeout(350);await mode(p,'blocks');const second=await state(p);await numeric(p).dispatchEvent('compositionstart');await numeric(p).fill('3');await (await reveal09(p.locator('#editorModecode'))).click();assert.equal((await state(p)).main.mode,'blocks');assert.deepEqual(stable(await state(p)),stable(second));await numeric(p).dispatchEvent('compositionend');await numeric(p).press('Enter');assert.equal((await state(p)).main.source,'点数を3にする。');return{codeAndBlockCompositionPreserved:true};});
  await run('callable-block-escape-cancels-inner-transaction',async p=>{
   await (await reveal09(p.locator('#procBtn'))).click();await (await reveal09(p.locator('#callableNewAction'))).click();await fill(p,'Escape試験','#callableName');await fill(p,'1と言う。\n2と言う。','#callableCode');await mode(p,'blocks',true);
   const croot=p.locator('#callableBlocks'),numbers=croot.locator('.blockui-node[data-schema-id="NumberLiteral"] [data-blockui-field="value"]'),before=await state(p);
   await numbers.first().fill('-');assert.ok(await p.evaluate(()=>!!Akari.app.editorState.draft.pendingEdit));await numbers.first().press('Escape');
   assert.equal(await p.locator('#procModal').isVisible(),true);assert.equal(await numbers.first().inputValue(),'1');assert.equal(await p.evaluate(()=>Akari.app.editorState.draft.pendingEdit),null);
   const afterInput=await state(p);for(const key of ['history','redo','dirty','hasDraft'])assert.equal(afterInput[key],before[key],key);assert.equal(afterInput.draft.source,before.draft.source);assert.equal(afterInput.callableDraft.source,before.callableDraft.source);
   const say=croot.locator('.blockui-node[data-schema-id="Say"]').first(),menu=say.locator(':scope > .blockui-node-head .blockui-actions');await U.openNodeMenu(say);assert.notEqual(await menu.getAttribute('open'),null);await p.keyboard.press('Escape');assert.equal(await p.locator('#procModal').isVisible(),true);assert.equal(await menu.getAttribute('open'),null);
   await U.nodeAction(say,'move');await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(await croot.evaluate(e=>e.contains(document.activeElement)),true,'move retains editor keyboard focus after hiding its menu');assert.equal(await croot.evaluate(e=>e.classList.contains('blockui-moving')),true);await p.keyboard.press('Escape');assert.equal(await p.locator('#procModal').isVisible(),true);assert.equal(await croot.evaluate(e=>e.classList.contains('blockui-moving')),false);
   const afterMove=await state(p);for(const key of ['history','redo','dirty','hasDraft'])assert.equal(afterMove[key],before[key],key);assert.equal(afterMove.draft.source,before.draft.source);assert.equal(afterMove.callableDraft.source,before.callableDraft.source);
   return{pendingInputEscapeCancelledWithoutClosing:true,openMenuEscapeCancelledWithoutClosing:true,statementMoveEscapeCancelledWithoutClosing:true,sourceHistoryRedoDirtyDraftPreserved:true};
  });
  await run('has-else-limit-refusal-restores-control',async p=>{
   const max=100000,prefix='もし 真なら、次のことをする。\n  「',suffix='」と言う。',fixed=[...prefix].length+[...suffix].length,source=prefix+'a'.repeat(max-fixed)+suffix;assert.equal([...source].length,max);await fill(p,source);await mode(p,'blocks');
   const ifNode=root(p).locator('.blockui-node[data-schema-id="IfStatement"]').first();await U.openNodeMenu(ifNode);const control=ifNode.locator('[data-blockui-field="hasElse"]');assert.equal(await control.inputValue(),'false');const before=await state(p),beforeTree=await p.evaluate(()=>JSON.stringify(Akari.app.editorState.main.blockView));
   await (await reveal09(control)).selectOption('true');await p.waitForTimeout(50);assert.equal(await control.inputValue(),'false');assert.deepEqual(stable(await state(p)),stable(before));assert.equal(await p.evaluate(()=>JSON.stringify(Akari.app.editorState.main.blockView)),beforeTree);assert.match(await root(p).locator('.blockui-message').textContent(),/上限/);
   return{sourceChars:max,elseInsertionRejected:true,controlRevertedToConfirmedAst:true,sourceBlockHistoryRedoDirtyPreserved:true};
  });
  await run('palette-generated-name-collision-boundary',async p=>{
   const chain=base=>Array.from({length:31},(_,i)=>base+'値'.repeat(i)),foreachNames=chain('項目'),foreachSource=foreachNames.map(name=>`名前一覧の各要素を${name}として、次のことをくり返す\n  何もしない。`).join('\n');
   await fill(p,foreachSource);await mode(p,'blocks');const mroot=root(p),main=await p.evaluate(()=>Akari.app.editorState.main),insert=mroot.locator('[data-blockui-action="body-insert"][data-parent-id="'+main.blockView.id+'"][data-blockui-body="body"]').last();await insert.click();await (await reveal09(mroot.locator('[data-blockui-search]'))).fill('ForEach');const eachButton=mroot.locator('[data-blockui-schema="ForEach"]');assert.equal(await eachButton.count(),1);assert.equal(await eachButton.isDisabled(),false,await eachButton.getAttribute('title'));await eachButton.click();const eachName=await p.evaluate(()=>Akari.app.editorState.main.blockView.bodies.body.at(-1).fields.binder);assert.ok([...eachName].length<=32);assert.equal(foreachNames.includes(eachName),false);
   await (await reveal09(p.locator('#procBtn'))).click();await (await reveal09(p.locator('#callableNewAction'))).click();await fill(p,'名前境界','#callableName');const argNames=chain('結果');await fill(p,argNames.join('、'),'#callableArgs');await fill(p,'','#callableCode');await mode(p,'blocks',true);const croot=p.locator('#callableBlocks'),add=async schema=>{await (await reveal09(croot.locator('[data-blockui-search]'))).fill(schema);const button=croot.locator('[data-blockui-schema="'+schema+'"]');assert.equal(await button.count(),1);assert.equal(await button.isDisabled(),false,await button.getAttribute('title'));await button.click();};
   await add('LocalVariableDeclaration');let draft=await p.evaluate(()=>Akari.app.editorState.draft),localVar=draft.blockView.bodies.body.find(n=>n.schemaId==='LocalVariableDeclaration').fields.name;assert.ok([...localVar].length<=32);assert.equal(argNames.includes(localVar),false);await croot.locator('[data-blockui-action="body-insert"][data-parent-id="'+draft.blockView.id+'"][data-blockui-body="body"]').last().click();await add('LocalListDeclaration');draft=await p.evaluate(()=>Akari.app.editorState.draft);const localList=draft.blockView.bodies.body.find(n=>n.schemaId==='LocalListDeclaration').fields.name;assert.ok([...localList].length<=32);assert.equal(argNames.includes(localList),false);assert.notEqual(localList,localVar);return{foreach:{used:foreachNames.length,generated:eachName},callable:{arguments:argNames.length,variable:localVar,list:localList},allGeneratedNamesWithin32:true,paletteInsertionsEnabled:true};
  });
  await run('callable-draft-history',async p=>{await (await reveal09(p.locator('#procBtn'))).click();await (await reveal09(p.locator('#callableNewFunction'))).click();await fill(p,'二倍','#callableName');await fill(p,'値','#callableArgs');await fill(p,'値×2を返す','#callableCode');const before=await state(p);assert.equal(JSON.parse(before.project).functions.length,0);await mode(p,'blocks',true);const n=p.locator('#callableBlocks .blockui-node[data-schema-id="NumberLiteral"] [data-blockui-field="value"]').first();await n.fill('3');await n.press('Enter');assert.equal(JSON.parse((await state(p)).project).functions.length,0);assert.ok((await state(p)).callableDraft.source.includes('3'));await (await reveal09(p.locator('#callableSave'))).click();const saved=await state(p);assert.equal(JSON.parse(saved.project).functions.length,1);assert.equal(saved.hasDraft,false);await p.keyboard.press('Control+z');const undone=await state(p);assert.equal(JSON.parse(undone.project).functions.length,0);assert.equal(undone.hasDraft,true);assert.equal(await p.locator('#procModal').getAttribute('class'),'modal show');await p.keyboard.press('Control+y');assert.equal(JSON.parse((await state(p)).project).functions.length,1);return{guiDraftNotRegisteredUntilSave:true,registrationUndoRestoresDraft:true};});
  await run('running-paused-lock-switch',async p=>{await fill(p,'点数を0にする。\n次のことをずっとくり返す。\n  点数に1を足す。\n  0.1秒待つ。');await mode(p,'blocks');await (await reveal09(p.locator('#runBtn'))).click();await p.waitForFunction(()=>Akari.app.editorState.state==='RUNNING');assert.equal(await root(p).locator('[data-blockui-field]').first().isDisabled(),true);assert.equal(await p.locator('#undoBtn').isDisabled(),true);await mode(p,'code');assert.equal(await p.locator('#codeEditor').isEditable(),false);await mode(p,'blocks');assert.equal((await state(p)).state,'RUNNING');await (await reveal09(p.locator('#pauseBtn'))).click();assert.equal((await state(p)).state,'PAUSED');await (await reveal09(p.locator('#stepBtn'))).click();assert.equal((await state(p)).state,'PAUSED');assert.ok(await root(p).locator('.blockui-current').count());const before=(await state(p)).project;await mode(p,'code');await mode(p,'blocks');assert.equal((await state(p)).project,before);assert.equal((await state(p)).state,'PAUSED');await (await reveal09(p.locator('#continueBtn'))).click();assert.equal((await state(p)).state,'RUNNING');await (await reveal09(p.locator('#stopBtn'))).click();assert.equal((await state(p)).state,'DESIGN');return{runPauseStepResumeStop:true,editingLockedBothModes:true,locationHighlighted:true};});
  await run('debug-function-owner',async p=>{await (await reveal09(p.locator('#procBtn'))).click();await (await reveal09(p.locator('#callableNewFunction'))).click();await fill(p,'失敗値','#callableName');await fill(p,'1÷0を返す。','#callableCode');await (await reveal09(p.locator('#callableSave'))).click();await (await reveal09(p.locator('#procClose'))).click();await fill(p,'失敗値（）と言う。');const before=(await state(p)).project;await (await reveal09(p.locator('#runBtn'))).click();await p.locator('#failureModal.show').waitFor();await (await reveal09(p.locator('#failureClose'))).click();assert.match((await state(p)).main.owner,/^function:/);await mode(p,'blocks');assert.equal((await state(p)).project,before);assert.ok(await root(p).locator('.blockui-current').count());await mode(p,'code');assert.equal((await state(p)).project,before);await (await reveal09(p.locator('#stopBtn'))).click();assert.equal((await state(p)).main.source,'失敗値（）と言う。');return{functionDebugOwner:true,noScriptOverwrite:true};});
  await run('draft-session-without-persistence',async p=>{
   await installStorageProbe(p);await p.reload();await p.waitForFunction(()=>!!Akari.app);
   const initial=await state(p);await fill(p,'点数を9にする。');await mode(p,'blocks');await blockEdit(p,8);
   await (await reveal09(p.locator('#procBtn'))).click();await (await reveal09(p.locator('#callableNewAction'))).click();
   await fill(p,'下書き','#callableName');await fill(p,'点数に2を足す。','#callableCode');await mode(p,'blocks',true);
   const before=await state(p);assert.equal(before.hasDraft,true);assert.equal(JSON.parse(before.project).actions.length,0);
   await p.waitForTimeout(1500);assert.deepEqual(stable(await state(p)),stable(before));await p.locator('#uiLevel').selectOption('all');const calls=await assertNoPersistence(p);
   await p.reload();await p.waitForFunction(()=>!!Akari.app);const after=await state(p);
   assert.equal(after.project,initial.project);assert.equal(after.hasDraft,false);assert.equal(await p.locator('#procModal').isVisible(),false);
   assert.equal(await p.locator('#uiLevel').inputValue(),'all');const startupCalls=await assertNoPersistence(p);return{uiPreferenceRetained:true,draftSeparateWhileEditing:true,noAutomaticDraftOrProjectPersistence:true,calls,startupCalls};
  });
  await run('responsive-mode-state',async p=>{await fill(p,'点数を3にする。\n次のことを10回くり返す。\n  点数に1を足す。');await mode(p,'blocks');const before=await state(p),dimensions=[];for(const[width,height]of [[1440,900],[1024,768],[768,1024],[600,800],[390,844],[320,568]]){await p.setViewportSize({width,height});await p.waitForTimeout(60);assert.deepEqual(stable(await state(p)),stable(before));const dim=await p.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth}));assert.ok(dim.scrollWidth<=width+1,JSON.stringify(dim));await (await reveal09(p.locator('#diagnoseBtn'))).click();await (await reveal09(p.locator('#diagnosisClose'))).click();await mode(p,'code');await mode(p,'blocks');dimensions.push(dim);}await p.setViewportSize({width:1440,height:900});await p.evaluate(()=>document.documentElement.style.zoom='2');await (await reveal09(p.locator('#diagnoseBtn'))).click();await (await reveal09(p.locator('#diagnosisClose'))).click();assert.deepEqual(stable(await state(p)),stable(before));return{dimensions,zoom200:true,modalAndSwitchControlsExercised:true};});
 }finally{await browser.close();}
 console.log(JSON.stringify({passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass).length,pageErrors:errors,networkRequests:network},null,2));if(results.some(r=>!r.pass)||errors.length||network.length)process.exitCode=1;
}
main().catch(e=>{console.error(e.message);process.exitCode=1;});


async function reveal09(locator){
 if(await locator.count()===1){if(!await locator.isVisible())for(const panel of await locator.locator('xpath=ancestor::*[contains(concat(" ",normalize-space(@class)," ")," blockui-side-folded ")]').all())await panel.locator('.blockui-side-toggle').click();const ancestors=locator.locator(await locator.evaluate(e=>e.tagName==='SUMMARY')?'xpath=parent::details/ancestor::details[not(@open)]':'xpath=ancestor::details[not(@open)]');for(const detail of await ancestors.all())await detail.locator(':scope > summary').click();}
 return locator;
}
