const L=require('./audit-lib.cjs'),assert=require('assert/strict'),{pathToFileURL}=require('url'),{chromium}=require('playwright');
const dir=L.path.resolve(process.argv[2]),manifest=L.verifyManifest(dir),url=pathToFileURL(L.path.join(dir,manifest.candidate)).href;
const results=[],errors=[],network=[];
const state=p=>p.evaluate(()=>{const a=Akari.app,s=a.editorState;return{project:JSON.stringify(a.project),source:s.main.sourceText,history:s.history,redo:s.redo,dirty:s.dirty,mode:s.main.mode};});
async function reveal(l){if(!await l.isVisible())for(const p of await l.locator('xpath=ancestor::*[contains(concat(" ",normalize-space(@class)," ")," blockui-side-folded ")]').all())await p.locator('.blockui-side-toggle').click();for(const d of await l.locator('xpath=ancestor::details[not(@open)]').all())await d.locator(':scope > summary').click();}
async function reach(l){await reveal(l);const page=l.page();for(let i=0;i<750&&!await l.evaluate(e=>e===document.activeElement);i++){const backwards=await l.evaluate(e=>!!(e.compareDocumentPosition(document.activeElement)&Node.DOCUMENT_POSITION_FOLLOWING));await page.keyboard.press(backwards?'Shift+Tab':'Tab');}assert(await l.evaluate(e=>e===document.activeElement),'keyboard reaches requested control');const b=await l.boundingBox();assert(b&&b.width&&b.height);assert(await l.evaluate(e=>{const r=e.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;return x>=0&&y>=0&&x<innerWidth&&y<innerHeight&&(e.contains(document.elementFromPoint(x,y))||document.elementFromPoint(x,y)===e);}),'visible unobstructed control');return b;}
async function click(l){await reach(l);await l.click();}
async function prop(p,name,value){const l=p.locator('#properties input[aria-label="'+name+'"]');await reveal(l);await l.fill(String(value));await l.press('Tab');}
const component=(p,id)=>p.evaluate(id=>structuredClone(Akari.app.project.components.find(c=>c.id===id)),id);
async function history(p,before,after){await p.locator('#undoBtn').click();assert.equal((await state(p)).project,before.project);await p.locator('#redoBtn').click();assert.equal((await state(p)).project,after.project);}
async function importFile(p,selector,file){const pending=p.waitForEvent('filechooser');await click(p.locator(selector));await(await pending).setFiles(L.path.join(__dirname,'media',file));await p.waitForFunction(()=>Akari.app.editorState.state==='DESIGN');}
async function resize(p,id){await p.waitForTimeout(300);const c=await component(p,id),before=await state(p),h=p.locator('[data-resize-for="'+id+'"][data-resize-direction="se"]'),b=await reach(h);await p.mouse.move(b.x+b.width/2,b.y+b.height/2);await p.mouse.down();await p.mouse.move(b.x+b.width/2+12,b.y+b.height/2+9,{steps:5});assert.equal((await state(p)).project,before.project,'preview does not commit');await p.mouse.up();const after=await state(p),d=await component(p,id);assert.notEqual(after.project,before.project);assert.equal(after.history,Math.min(30,before.history+1));assert(d.w!==c.w||d.h!==c.h||d.scalePercent!==c.scalePercent);if(d.w!==c.w||d.h!==c.h){const corner=c=>{const r=c.direction*Math.PI/180,s=c.scalePercent/100;return{x:c.x+c.w/2+(-c.w*Math.cos(r)+c.h*Math.sin(r))*s/2,y:c.y+c.h/2+(-c.w*Math.sin(r)-c.h*Math.cos(r))*s/2};},a=corner(c),b=corner(d);assert(Math.hypot(a.x-b.x,a.y-b.y)<.01,'opposite corner remains fixed under rotation and stage scale');}else{assert.equal(d.w/c.w,d.h/c.h);assert.equal(d.x,c.x);assert.equal(d.y,c.y);}await history(p,before,after);
 const cancelBefore=await state(p),hb=await reach(h);await p.mouse.move(hb.x+hb.width/2,hb.y+hb.height/2);await p.mouse.down();await p.mouse.move(hb.x+15,hb.y+10,{steps:3});await p.keyboard.press('Escape');await p.mouse.up();assert.deepEqual(await state(p),cancelBefore);
 const touchBefore=await state(p),tb=await reach(h),cdp=await p.context().newCDPSession(p);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:tb.x+tb.width/2,y:tb.y+tb.height/2,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:tb.x+tb.width/2+10,y:tb.y+tb.height/2+10,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await cdp.detach();assert.deepEqual(await state(p),touchBefore);const keyBefore=await state(p);await h.press('ArrowRight');const keyAfter=await state(p);assert.equal(keyAfter.history,Math.min(30,keyBefore.history+1));await history(p,keyBefore,keyAfter);return{id,before:c,after:d,pointer:true,previewAtomic:true,escape:true,keyboard:true,undoRedo:true};}
async function resizeBounds(p,id){const c=await component(p,id),h=p.locator('[data-resize-for="'+id+'"][data-resize-direction="se"]'),scale=c.type==='sprite'&&c.costumes.find(x=>x.id===c.costumeId)?.kind==='text';await prop(p,'方向',0);if(scale){for(const [value,x,y,key]of [[1,180,100,'ArrowLeft'],[1000,-200,-200,'ArrowRight']]){await prop(p,'左',x);await prop(p,'上',y);await prop(p,'大きさ%',value);await p.waitForTimeout(300);await reach(h);const before=await state(p);await h.press(key);assert.deepEqual(await state(p),before);assert.equal((await component(p,id)).scalePercent,value);}}else{await prop(p,'大きさ%',100);for(const [value,x,y,key]of [[8,180,100,'ArrowLeft'],[1200,-800,-1000,'ArrowRight']]){await prop(p,'左',x);await prop(p,'上',y);await prop(p,'幅',value);await prop(p,'高さ',value);await p.waitForTimeout(300);await reach(h);const before=await state(p);await h.press(key);assert.deepEqual(await state(p),before);assert.equal((await component(p,id)).w,value);}}for(const [label,key]of [['左','x'],['上','y'],['幅','w'],['高さ','h'],['方向','direction'],['大きさ%','scalePercent']]){if(scale&&['w','h'].includes(key))continue;await prop(p,label,c[key]);}await p.waitForTimeout(300);if(!scale){const before=await state(p),original=await component(p,id),b=await reach(h);await p.keyboard.down('Shift');await p.mouse.move(b.x+b.width/2,b.y+b.height/2);await p.mouse.down();await p.mouse.move(b.x+b.width/2+13,b.y+b.height/2+7,{steps:4});await p.mouse.up();await p.keyboard.up('Shift');const changed=await component(p,id);assert(Math.abs(changed.w/changed.h-original.w/original.h)<1e-6);await history(p,before,await state(p));}return{min:true,max:true,keyboardBoundaryNoOp:true,shiftRatio:!scale};}
(async()=>{const browser=await chromium.launch({executablePath:process.env.AKARI_BROWSER,headless:true});try{
for(const viewport of [{width:1366,height:768},{width:768,height:1024},{width:390,height:844}])for(const mode of ['code','blocks']){
 const context=await browser.newContext({viewport,acceptDownloads:true,hasTouch:true}),p=await context.newPage();p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.stack));let acceptDialog=true;p.on('dialog',d=>acceptDialog?d.accept():d.dismiss());await p.route(/^https?:/,r=>{network.push(r.request().url());return r.abort();});await p.goto(url);await p.locator('#editorMode'+mode).click();
 const run=async(id,fn)=>{try{results.push({id,viewport,mode,pass:true,evidence:await fn()});}catch(e){results.push({id,viewport,mode,pass:false,error:e.stack});await p.screenshot({path:L.path.join(dir,id+'-'+viewport.width+'-'+mode+'.png')});}L.result(L.path.join(dir,'modern-browser.json'),{manifest,browser:browser.version(),results,errors,network});};
 await run('DESIGN09-STANDARD-SPRITES',async()=>{const source=L.read(L.path.join(dir,manifest.candidate)),vm=require('vm'),sandbox={Object,STANDARD_AKARI_MASCOT:{kind:'image'}};const match=source.match(/const STANDARD_SPRITES\s*=\s*Object.freeze\(\s*(\{[\s\S]*?\})\s*\);/);assert(match);const registry=vm.runInNewContext('('+match[1]+')',sandbox);const buttons=p.locator('[data-sprite-preset]'),ids=await buttons.evaluateAll(ns=>ns.map(n=>n.dataset.spritePreset));assert.equal(new Set(ids).size,ids.length);assert.deepEqual(ids.slice().sort(),Object.keys(registry).sort());const images=p.locator('[data-sprite-preset] img');assert.equal(await images.count(),Object.values(registry).filter(v=>v.kind==='image').length);await p.waitForFunction(()=>[...document.querySelectorAll('[data-sprite-preset] img')].every(e=>e.complete&&e.naturalWidth>0&&e.naturalHeight>0));return{count:ids.length,unique:true,allRegistered:true,imagePresetsDecoded:await images.count()};});
 await run('DESIGN09-COMPONENT-REACHABILITY',async()=>{const before=await state(p);if(mode==='blocks')await p.locator('#componentPickerCore > summary').click();for(const d of await p.locator('.sprite-preset-category').all())if(await d.getAttribute('open')===null)await d.locator(':scope > summary').click();const choices=p.locator('[data-sprite-preset]'),n=await choices.count(),observed=[];for(const i of [0,Math.floor(n/2),n-1]){const l=choices.nth(i);await reach(l);observed.push(await l.getAttribute('data-sprite-preset'));}assert.deepEqual(await state(p),before);const last=choices.last(),preset=await last.getAttribute('data-sprite-preset'),glyph=await last.locator('.ico').innerText();await click(last);const id=await p.locator('#objectSelect').inputValue(),c=await component(p,id);assert.equal(c.costumes[0].value,glyph);assert.equal(c.text,glyph);assert.equal((await state(p)).mode,mode);return{observed,preset,id,glyph};});
 await run('DESIGN09-RESIZE-POINTER',async()=>{const out=[];for(const type of ['label','button','input','box','sprite']){const tool=type==='sprite'?p.locator('[data-sprite-preset="star"]'):p.locator('.tool[data-type="'+type+'"]');await click(tool);const id=await p.locator('#objectSelect').inputValue();await prop(p,'左',180);await prop(p,'上',100);await prop(p,'方向',30);await prop(p,'大きさ%',120);out.push({...await resize(p,id),bounds:await resizeBounds(p,id)});}return out;});
 await run('DESIGN09-COLOR-COMMIT-CANCEL',async()=>{await click(p.locator('.tool[data-type="box"]'));const id=await p.locator('#objectSelect').inputValue();for(const field of ['fg','bg']){const root=p.locator('[data-color-field="'+field+'"]');if(!await root.count())continue;const before=await state(p);await click(root.locator('[data-color-value]').first());const basic=await state(p);if(basic.project!==before.project)await history(p,before,basic);await click(root.locator('.color-more'));const previewBefore=await state(p);await p.locator('#colorAdvanced > summary').click();await p.locator('#colorHex').fill('#123456');await p.locator('#colorValueCore').press('ArrowLeft');assert.deepEqual(await state(p),previewBefore);await p.locator('#colorCancel').click();assert.deepEqual(await state(p),previewBefore);await click(root.locator('.color-more'));await p.locator('#colorAdvanced > summary').click();await p.locator('#colorHex').fill('#123456');await p.locator('#colorConfirm').click();assert.equal((await component(p,id))[field],'#123456');const after=await state(p);assert.equal(after.history,Math.min(30,previewBefore.history+1));await history(p,previewBefore,after);if(field==='bg'){await click(root.locator('.color-none'));assert.equal((await component(p,id)).bg,null);}}return{basic:true,hex:true,brightness:true,previewAndCancelAtomic:true,history:true,transparent:true};});
 await run('DESIGN09-MEDIA-ENTRYPOINTS',async()=>{await importFile(p,'#imageObjectAdd','picture.png');const id=await p.locator('#objectSelect').inputValue();assert.equal((await component(p,id)).costumes[0].kind,'image');await resize(p,id);await click(p.locator('#assetBtn'));await importFile(p,'#backdropImageAdd','picture.jpg');await importFile(p,'#costumeImageAdd','picture.webp');await importFile(p,'#soundAdd','tone.wav');await p.locator('#assetClose').click();return{id,object:true,backdrop:true,costume:true,sound:true,realFileChooser:true};});
 await run('DESIGN09-DELETE-UNDO',async()=>{const id=await p.locator('#objectSelect').inputValue(),before=await state(p);acceptDialog=false;await click(p.locator('#properties button').filter({hasText:'部品を削除'}));assert.deepEqual(await state(p),before);acceptDialog=true;await click(p.locator('#properties button').filter({hasText:'部品を削除'}));assert.equal(await component(p,id),undefined);const after=await state(p);await history(p,before,after);return{id,removed:true,undoRedo:true};});
 await run('DESIGN09-MIXED-HISTORY-STORAGE',async()=>{const before=await state(p),download=p.waitForEvent('download');await p.locator('#saveBtn').click();const d=await download,file=L.path.join(dir,'modern-'+viewport.width+'-'+mode+'.akari.md');await d.saveAs(file);await p.locator('#newBtn').click();await p.locator('#fileInput').setInputFiles(file);await p.waitForFunction(expected=>JSON.stringify(Akari.app.project)===expected,before.project);await p.locator('#runBtn').click();assert.equal(await p.locator('.design-resize-handle').count(),0);await p.locator('#stopBtn').click();assert.equal((await state(p)).project,before.project);return{realSaveReload:true,designRuntimeSeparated:true};});
 await context.close();
}
}finally{await browser.close();}if(results.some(r=>!r.pass)||errors.length||network.length)process.exitCode=1;console.log(JSON.stringify({passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass).length,errors,network}));})().catch(e=>{console.error(e);process.exitCode=1;});
