const U=require('./ui-routes.cjs');
const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict'),{pathToFileURL}=require('url');
const{chromium}=require('playwright');
const html=path.resolve(process.argv[2]||'Akari.html'),output=path.resolve(process.argv[3]||'audit-evidence/browser/parent-qa.json');
(async()=>{const browser=await chromium.launch({executablePath:(process.env.AKARI_BROWSER||undefined),headless:true,args:['--allow-file-access-from-files']});const results=[];try{const test=async(id,fn)=>{const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.stack));page.on('dialog',d=>d.accept());try{await page.goto(pathToFileURL(html).href);await fn(page);assert.deepEqual(errors,[]);results.push({id,pass:true});}catch(e){results.push({id,pass:false,error:e.stack,pageErrors:errors});await page.screenshot({path:path.join(path.dirname(output),id+'.png'),fullPage:true});}finally{await page.close();}console.log(results.at(-1));};
const state=p=>p.evaluate(()=>{const a=Akari.app,s=a.editorState;return{source:s.main.sourceText,owner:s.main.ownerKey,mode:s.main.mode,project:JSON.stringify(a.project),history:s.history,redo:s.redo,dirty:s.dirty,draft:s.callableDraft,hasDraft:s.hasDraft};});
const field=p=>p.locator('#blockEditor article[data-schema-id="NumberLiteral"] input[data-blockui-field="value"]').first();
await test('parent-switch-edit-history',async p=>{const src='※  空白を保持\n\n点数を１にする\n点数と言う ※末尾 ';
 const initialHistory=(await state(p)).history;await (await reveal09(p.locator('#codeEditor'))).fill(src);await p.waitForFunction(({src,initialHistory})=>{const s=Akari.app.editorState;return s.main.sourceText===src&&s.history===initialHistory+1;},{src,initialHistory});const before=await state(p);await (await reveal09(p.locator('#editorModeblocks'))).click();await (await reveal09(p.locator('#editorModecode'))).click();assert.deepEqual(await state(p),before);
 await (await reveal09(p.locator('#editorModeblocks'))).click();await field(p).fill('7');await field(p).press('Enter');assert.equal((await state(p)).source.includes('7'),true);assert.equal((await state(p)).history,before.history+1);
 await (await reveal09(p.locator('#undoBtn'))).click();assert.equal((await state(p)).source,src);await (await reveal09(p.locator('#redoBtn'))).click();assert.match((await state(p)).source,/7/);
});
await test('parent-pending-keeps-owner',async p=>{await (await reveal09(p.locator('#codeEditor'))).fill('点数を1にする');await p.waitForTimeout(350);await (await reveal09(p.locator('#editorModeblocks'))).click();const before=await state(p);await field(p).fill('');await (await reveal09(p.locator('#editorModecode'))).click();assert.deepEqual(await state(p),before);await (await reveal09(p.locator('#objectSelect'))).selectOption('sprite-1');assert.deepEqual(await state(p),before);await (await reveal09(p.locator('#editorCancel'))).click();await (await reveal09(p.locator('#editorModecode'))).click();assert.equal(await p.locator('#codeEditor').inputValue(),before.source);});
await test('parent-definition-draft',async p=>{await (await reveal09(p.locator('#procBtn'))).click();await (await reveal09(p.locator('#callableNewAction'))).click();await (await reveal09(p.locator('#callableName'))).fill('増やす');await (await reveal09(p.locator('#callableArgs'))).fill('量');await (await reveal09(p.locator('#callableCode'))).fill('点数に量を足す');await p.waitForTimeout(350);assert.equal((await state(p)).draft.source,'点数に量を足す');assert.equal((await state(p)).hasDraft,true);assert.equal(await p.evaluate(()=>Akari.app.project.actions.length),0);
 await (await reveal09(p.locator('#callableModeblocks'))).click();await (await reveal09(p.locator('#callableModecode'))).click();assert.equal(await p.locator('#callableCode').inputValue(),'点数に量を足す');await (await reveal09(p.locator('#callableSave'))).click();assert.equal(await p.evaluate(()=>Akari.app.project.actions[0]?.source),'点数に量を足す');assert.equal((await state(p)).hasDraft,false);
 await (await reveal09(p.locator('#callableCode'))).fill('点数に2を足す');await p.waitForTimeout(350);await (await reveal09(p.locator('#callableModeblocks'))).click();const n=p.locator('#callableBlocks article[data-schema-id="NumberLiteral"] input[data-blockui-field="value"]').first();await n.fill('4');await n.press('Enter');assert.equal((await state(p)).draft.source.includes('4'),true);assert.equal(await p.evaluate(()=>Akari.app.project.actions[0]?.source),'点数に量を足す');await (await reveal09(p.locator('#callableSave'))).click();assert.match(await p.evaluate(()=>Akari.app.project.actions[0]?.source),/4/);
 await p.locator('#callableName').press('Control+z');assert.equal((await state(p)).hasDraft,true);assert.equal(await p.evaluate(()=>Akari.app.project.actions[0]?.source),'点数に量を足す');await p.locator('#callableName').press('Control+y');assert.equal((await state(p)).hasDraft,false);assert.match(await p.evaluate(()=>Akari.app.project.actions[0]?.source),/4/);
});
await test('parent-syntax-semantic-switch',async p=>{await (await reveal09(p.locator('#codeEditor'))).fill('未定義の値と言う');await (await reveal09(p.locator('#editorModeblocks'))).click();assert.equal((await state(p)).mode,'blocks');assert.match(await p.locator('#blockEditor').innerText(),/診断/);await (await reveal09(p.locator('#editorModecode'))).click();await (await reveal09(p.locator('#codeEditor'))).fill('点数を');await p.waitForTimeout(200);assert.equal(await p.locator('#editorModeblocks').isDisabled(),true);assert.equal((await state(p)).source,'点数を');});
await test('parent-code-native-history',async p=>{const initial=(await state(p)).source;await (await reveal09(p.locator('#codeEditor'))).fill('点数を2にする');await p.waitForTimeout(350);await p.locator('#codeEditor').press('Control+z');assert.equal((await state(p)).source,initial);await p.locator('#codeEditor').press('Control+y');assert.equal((await state(p)).source,'点数を2にする');await p.locator('#codeEditor').press('Control+z');await (await reveal09(p.locator('#codeEditor'))).fill('点数を3にする');assert.equal((await state(p)).redo,0);});
await test('parent-syntax-undo-fallback',async p=>{await (await reveal09(p.locator('#codeEditor'))).fill('壊れた構文');await p.waitForTimeout(350);await (await reveal09(p.locator('#codeEditor'))).fill('何もしない。');await p.waitForTimeout(350);await (await reveal09(p.locator('#editorModeblocks'))).click();await (await reveal09(p.locator('#undoBtn'))).click();assert.equal((await state(p)).mode,'code');assert.equal(await p.locator('#codeEditor').inputValue(),'壊れた構文');assert.equal(await p.locator('#codeEditor').isVisible(),true);});
await test('parent-pending-header-owner',async p=>{await (await reveal09(p.locator('#procBtn'))).click();await (await reveal09(p.locator('#callableNewAction'))).click();await (await reveal09(p.locator('#callableName'))).fill('試験');await (await reveal09(p.locator('#callableCode'))).fill('1と言う。\n2と言う。');await (await reveal09(p.locator('#callableModeblocks'))).click();await U.nodeAction(p.locator('#callableBlocks article[data-schema-id="Say"]').first(),'duplicate');const fields=p.locator('#callableBlocks article[data-schema-id="NumberLiteral"] input[data-blockui-field="value"]');assert.equal(await fields.count(),3);await fields.last().fill('');await (await reveal09(p.locator('#callableName'))).fill('変更');assert.equal(await p.locator('#callableName').inputValue(),'試験');await fields.last().fill('9');await fields.last().press('Enter');assert.equal((await state(p)).draft.source,'1と言う。\n1と言う。\n9と言う。');});
await test('parent-header-limit-switch',async p=>{await (await reveal09(p.locator('#procBtn'))).click();await (await reveal09(p.locator('#callableCode'))).fill('1と言う。');await (await reveal09(p.locator('#callableName'))).fill('名'.repeat(501));const before=await state(p);await (await reveal09(p.locator('#callableModeblocks'))).click();assert.equal(await p.evaluate(()=>Akari.app.editorState.draft.mode),'code');assert.equal((await p.locator('#callableName').inputValue()).length,501);assert.deepEqual(await state(p),before);await (await reveal09(p.locator('#callableCancel'))).click();assert.equal(await p.locator('#callableName').inputValue(),'');});
await test('parent-tool-drag-pending',async p=>{await (await reveal09(p.locator('#editorModeblocks'))).click();await p.locator('#componentPickerCore > summary').click();const before=await state(p);await field(p).fill('');await (await reveal09(p.locator('.tool[data-type="label"]'))).dragTo(p.locator('#formSurface'));assert.deepEqual(await state(p),before);assert.equal(await field(p).inputValue(),'');});
fs.writeFileSync(output,JSON.stringify({html,sha256:crypto.createHash('sha256').update(fs.readFileSync(html)).digest('hex'),browser:browser.version(),results},null,2));if(results.some(x=>!x.pass))process.exitCode=1;
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});


async function reveal09(locator){
 if(await locator.count()===1){if(!await locator.isVisible())for(const panel of await locator.locator('xpath=ancestor::*[contains(concat(" ",normalize-space(@class)," ")," blockui-side-folded ")]').all())await panel.locator('.blockui-side-toggle').click();const ancestors=locator.locator(await locator.evaluate(e=>e.tagName==='SUMMARY')?'xpath=parent::details/ancestor::details[not(@open)]':'xpath=ancestor::details[not(@open)]');for(const detail of await ancestors.all())await detail.locator(':scope > summary').click();}
 return locator;
}
