const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('playwright');
const html=path.resolve(process.argv[2]||'Akari.html'),prefix=path.resolve(process.argv[3]||'audit-evidence/browser/shell-'+Date.now());
(async()=>{const bytes=fs.readFileSync(html),b=await chromium.launch({executablePath:(process.env.AKARI_BROWSER||undefined),headless:true}),results=[],errors=[],network=[];try{
 const p=await b.newPage({viewport:{width:1440,height:1000}});p.on('pageerror',e=>errors.push(e.stack));p.on('dialog',d=>d.accept());await p.route(/^https?:/,r=>{network.push(r.request().url());return r.abort();});
 const state=()=>p.evaluate(()=>{const a=Akari.app,s=a.editorState;return{source:s.main.sourceText,project:JSON.stringify(a.project),history:s.history,redo:s.redo,dirty:s.dirty};});
 const test=async(id,fn)=>{try{results.push({id,pass:true,evidence:await fn()});}catch(e){results.push({id,pass:false,error:e.stack});}console.log(results.at(-1));};
 await p.goto(pathToFileURL(html).href);
 await test('mock-desktop-code-layout',async()=>{const m=await p.evaluate(()=>{const rect=s=>{const r=document.querySelector(s).getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height,b:r.bottom};};return{toolbar:rect('.menutool'),designer:rect('#designerWindow'),editor:rect('.codewin'),side:rect('.side'),mode:rect('.editor-modes'),bodyHeight:document.body.scrollHeight,hints:document.querySelector('#hintsDisclosure').open,output:document.querySelector('.output-disclosure').open};});assert(m.toolbar.h<80);assert(m.editor.y>=m.designer.b-1);assert(m.side.x>m.designer.x);assert(m.mode.y<80);assert(m.bodyHeight<=1002);assert(!m.hints&&!m.output);await p.screenshot({path:prefix+'-code.png',fullPage:true});return m;});
 await test('mock-block-layout-source-invariant',async()=>{const before=await state();await (await reveal09(p.locator('#editorModeblocks'))).click();assert.deepEqual(await state(),before);const m=await p.evaluate(()=>{const rect=s=>{const r=document.querySelector(s).getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height,b:r.bottom};};return{palette:rect('#blockEditor .blockui-palette'),workspace:rect('#blockEditor .blockui-workspace'),stage:rect('#designerWindow'),parts:rect('.objects-window'),mode:document.body.dataset.editorMode,pressed:document.querySelector('#editorModeblocks').getAttribute('aria-pressed'),bodyHeight:document.body.scrollHeight};});assert.equal(m.mode,'blocks');assert.equal(m.pressed,'true');assert(m.palette.x<m.workspace.x&&m.workspace.x<m.stage.x);assert(m.palette.y>=0&&m.palette.b<=1002&&m.palette.h>100);assert(Math.abs(m.palette.y-m.workspace.y)<2,'palette and workspace share the current workbench row');assert(m.parts.x>=m.workspace.x+m.workspace.w-2&&m.parts.b<=1002&&m.parts.h>0,'objects stay in the separate right column within the viewport');assert(m.bodyHeight<=1002);await p.screenshot({path:prefix+'-blocks.png',fullPage:true});await (await reveal09(p.locator('#editorModecode'))).click();assert.deepEqual(await state(),before);return m;});
 await test('disclosure-discoverability-source-invariant',async()=>{await (await reveal09(p.locator('#codeEditor'))).fill('');await p.waitForTimeout(350);await p.waitForTimeout(350);const before=await state();await (await reveal09(p.locator('#hintsDisclosure summary'))).click();assert(await p.locator('#hintSearch').isVisible());await (await reveal09(p.locator('#hintSearch'))).fill('何もしない');assert((await p.locator('#codeHints').innerText()).includes('何もしない'));await (await reveal09(p.locator('#hintsDisclosure summary'))).click();await (await reveal09(p.locator('.output-disclosure summary'))).click();assert(await p.locator('#console').isVisible());assert.deepEqual(await state(),before);return{hintSearchReachable:true,outputReachable:true};});
 await test('six-width-layout',async()=>{const widths=[1440,1024,768,600,390,320],out=[];for(const width of widths){await p.setViewportSize({width,height:900});for(const mode of ['code','blocks']){await p.locator('#editorMode'+mode).click();const before=await state(),v=await p.evaluate(()=>({width:innerWidth,documentWidth:document.documentElement.scrollWidth,mode:document.body.dataset.editorMode}));assert(v.documentWidth<=width+1,JSON.stringify(v));assert(await p.locator('#editorModecode').isVisible());assert(await p.locator('#editorModeblocks').isVisible());assert.deepEqual(await state(),before);out.push(v);}await p.screenshot({path:prefix+'-'+width+'.png',fullPage:true});}return out;});
}finally{await b.close();fs.writeFileSync(prefix+'.json',JSON.stringify({html,sha256:crypto.createHash('sha256').update(bytes).digest('hex'),sourceUnchanged:bytes.equals(fs.readFileSync(html)),results,pageErrors:errors,networkRequests:network,browser:b.version()},null,2));}if(errors.length||network.length||results.some(r=>!r.pass))process.exitCode=1;})();


async function reveal09(locator){
 if(await locator.count()===1){if(!await locator.isVisible())for(const panel of await locator.locator('xpath=ancestor::*[contains(concat(" ",normalize-space(@class)," ")," blockui-side-folded ")]').all())await panel.locator('.blockui-side-toggle').click();const ancestors=locator.locator(await locator.evaluate(e=>e.tagName==='SUMMARY')?'xpath=parent::details/ancestor::details[not(@open)]':'xpath=ancestor::details[not(@open)]');for(const detail of await ancestors.all())await detail.locator(':scope > summary').click();}
 return locator;
}
