// Actual local-file pointer and keyboard coverage, bound to the captured commit.
const L=require('./audit-lib.cjs'),U=require('./ui-routes.cjs'),assert=require('assert/strict'),{chromium}=require('playwright'),{pathToFileURL}=require('url');
const dir=L.path.resolve(process.argv[2]),manifest=L.verifyManifest(dir),results=[],errors=[],network=[];
const comparable=v=>JSON.parse(JSON.stringify(v,(key,value)=>['sourceSpan','endLine','raw','source'].includes(key)?undefined:value));
const state=p=>p.evaluate(()=>{const a=Akari.app,s=a.editorState;return{source:s.main.sourceText,project:JSON.stringify(a.project),history:s.history,redo:s.redo,dirty:s.dirty,ast:s.main.syntaxAst};});
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.AKARI_BROWSER});try{for(const viewport of [{width:1366,height:768},{width:768,height:1024},{width:390,height:844}]){
 const c=await browser.newContext({viewport}),p=await c.newPage();p.setDefaultTimeout(15000);p.on('pageerror',e=>errors.push(e.message));await p.route(/^https?:/,r=>{network.push(r.request().url());return r.abort();});
 try{
 await p.goto(pathToFileURL(L.path.join(dir,manifest.candidate)).href);const source='次のことを2回くり返す。 ※ 囲い\n  もし 真なら、次のことをする。\n    1＋2と言う。 ※ 中身\n    何もしない。\n  何もしない。\n9と言う。';
 const initial=await state(p);await p.locator('#codeEditor').fill(source);await p.waitForFunction(h=>Akari.app.editorState.history===h+1,initial.history);await p.locator('#editorModeblocks').click();const root=p.locator('#blockEditor'),world=root.locator('.blockui-workspace');await root.locator('[data-blockui-action="workspace-expand"]').click();await root.locator('[data-blockui-action="library-toggle"]').click();
 await p.waitForFunction(()=>[...document.querySelectorAll('#blockEditor .blockui-node[data-schema-id][data-shape-kind],#blockEditor .blockui-event-hat[data-shape-kind]')].filter(e=>e.offsetWidth&&e.offsetHeight).every(e=>e.querySelector(':scope > .blockui-shape path')?.getAttribute('d')));
 const shapes=await root.locator('.blockui-node[data-schema-id][data-shape-kind],.blockui-event-hat[data-shape-kind]').evaluateAll(ns=>ns.filter(n=>n.offsetWidth&&n.offsetHeight).map(n=>({schema:n.classList.contains('blockui-event-hat')?'event-hat':n.dataset.schemaId,kind:n.dataset.shapeKind,path:n.querySelector(':scope > .blockui-shape path')?.getAttribute('d'),width:n.offsetWidth,height:n.offsetHeight})));
 const expectedShapes={'RepeatCount':'stack','IfStatement':'stack','BooleanLiteral':'boolean','BinaryExpression:ADD':'value','NumberLiteral':'value','Say':'stack','NoOperation':'stack','event-hat':'hat'};
 for(const [schema,kind] of Object.entries(expectedShapes)){const found=shapes.filter(s=>s.schema===schema);assert(found.length,'shape missing '+schema);for(const shape of found){assert.equal(shape.kind,kind);assert(shape.path&&shape.path.endsWith('Z'));assert(shape.width>0&&shape.height>0);}}
 assert.equal(await root.locator('.blockui-event-hat').count(),1);assert((await root.locator('.blockui-event-hat').innerText()).includes('開始'));await p.screenshot({path:L.path.join(dir,'shape-meaning-'+viewport.width+'.png')});
 results.push({id:'WB09-SHAPE-MEANING:'+viewport.width,pass:true,viewport,shapes,ownerHeading:true});
 const before=await state(p),say=root.locator('.blockui-node[data-schema-id="Say"]').first();await U.nodeAction(say,'move');await root.locator('.blockui-script > .blockui-node-content > .blockui-body > [data-insert-index="2"]').click();const moved=await state(p);assert.equal(moved.ast.body.length,3);assert.equal(moved.ast.body[0].body[0].thenBody.length,1);assert.equal(moved.ast.body[2].value.kind,'BinaryExpression');assert(moved.ast.body[2].inlineComment.includes('中身'));assert.equal(moved.history,before.history+1);await p.locator('#undoBtn').click();assert.equal((await state(p)).source,before.source);await p.locator('#redoBtn').click();assert.equal((await state(p)).source,moved.source);
 const repeat=root.locator('.blockui-node[data-schema-id="RepeatCount"]').first();await U.nodeAction(repeat.locator('.blockui-node[data-schema-id="IfStatement"]').first(),'collapse');const handle=repeat.locator(':scope > .blockui-node-content > .blockui-node-main > .blockui-phrase-text').first(),drop=root.locator('.blockui-script > .blockui-node-content > .blockui-body > [data-insert-index="3"]');await handle.scrollIntoViewIfNeeded();let h=await handle.boundingBox(),d=await drop.boundingBox();await p.mouse.move(h.x+h.width/2,h.y+h.height/2);await p.mouse.down();await p.mouse.move(d.x+20,d.y+d.height/2,{steps:8});await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));d=await drop.boundingBox();await p.mouse.move(d.x+20,d.y+d.height/2);assert.equal(await root.locator('.blockui-drop-preview').count(),1);assert.equal((await state(p)).source,moved.source);await p.screenshot({path:L.path.join(dir,'direct-preview-'+viewport.width+'.png')});await p.mouse.up();const grouped=await state(p);assert.deepEqual(grouped.ast.body.map(n=>n.kind),['Say','Say','RepeatCount']);assert.deepEqual(comparable(grouped.ast.body[2].body),comparable(moved.ast.body[0].body));assert.equal(grouped.ast.body[2].inlineComment,moved.ast.body[0].inlineComment);await p.locator('#undoBtn').click();assert.equal((await state(p)).source,moved.source);await p.locator('#redoBtn').click();assert.equal((await state(p)).source,grouped.source);
 // Pan uses actual background pointer input; no scrollTop mutation or synthetic edit.
 await p.locator('#editorModecode').click();const panHistory=(await state(p)).history;await p.locator('#codeEditor').fill(Array(80).fill('何もしない。').join('\n'));await p.waitForFunction(h=>Akari.app.editorState.history===h+1,panHistory);await p.locator('#editorModeblocks').click();
 await root.locator('[data-blockui-action="workspace-home"]').click();const stable=await state(p),panPoint=await world.evaluate(w=>{const r=w.getBoundingClientRect();for(let y=r.top+30;y<r.bottom-70;y+=12)for(let x=r.left+8;x<r.right-20;x+=12){const e=document.elementFromPoint(x,y);if(e&&w.contains(e)&&!e.closest('.blockui-node,.blockui-event-hat,button,input,select,textarea,summary,a'))return{x,y};}return null;});assert(panPoint,'visible background for panning');const scrollBefore=await world.evaluate(e=>({x:e.scrollLeft,y:e.scrollTop}));await p.mouse.move(panPoint.x,panPoint.y);await p.mouse.down();assert.equal(await world.evaluate(e=>e.classList.contains('blockui-panning')),true);await p.mouse.move(panPoint.x-40,panPoint.y-70,{steps:5});await p.mouse.up();const scrollAfter=await world.evaluate(e=>({x:e.scrollLeft,y:e.scrollTop}));assert(scrollAfter.x>scrollBefore.x||scrollAfter.y>scrollBefore.y,'pan changes viewport');assert.deepEqual(await state(p),stable);
 await root.locator('[data-blockui-action="workspace-home"]').click();assert.equal(await world.evaluate(e=>e.scrollTop),0);await root.locator('[data-blockui-action="zoom-in"]').click();await root.locator('[data-blockui-action="zoom-out"]').click();assert.deepEqual(await state(p),stable);await p.screenshot({path:L.path.join(dir,'direct-final-'+viewport.width+'.png')});results.push({id:'WB09-DIRECT:'+viewport.width,pass:true,viewport,nestedMove:true,groupPointer:true,comments:true,history:true,pan:true,zoom:true,sourceImmutableDuringPreview:true});
 }catch(e){results.push({id:'WB09-DIRECT:'+viewport.width,pass:false,viewport,error:e.stack});await p.screenshot({path:L.path.join(dir,'direct-fail-'+viewport.width+'.png')});}finally{await c.close();L.result(L.path.join(dir,'workbench-direct.json'),{manifest,browser:browser.version(),results,errors,network});}
}}finally{await browser.close();}console.log(JSON.stringify(results));if(results.some(r=>!r.pass)||errors.length||network.length)process.exitCode=1;})().catch(e=>{console.error(e);process.exitCode=1});
