const L=require('./audit-lib.cjs'),U=require('./ui-routes.cjs'),assert=require('assert/strict'),{chromium}=require('playwright'),{pathToFileURL}=require('url');
const dir=L.path.resolve(process.argv[2]),manifest=L.verifyManifest(dir),results=[],errors=[],network=[];
async function tabTo(l){const p=l.page();for(let i=0;i<1000&&!await l.evaluate(e=>e===document.activeElement);i++){const back=await l.evaluate(e=>!!(e.compareDocumentPosition(document.activeElement)&Node.DOCUMENT_POSITION_FOLLOWING));await p.keyboard.press(back?'Shift+Tab':'Tab');}assert(await l.evaluate(e=>e===document.activeElement));}
const state=p=>p.evaluate(()=>{const s=Akari.app.editorState;return{source:s.main.sourceText,history:s.history,redo:s.redo,dirty:s.dirty,mode:s.main.mode,ast:s.main.syntaxAst};});
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.AKARI_BROWSER});try{for(const viewport of [{width:1366,height:768},{width:768,height:1024},{width:390,height:844}])for(const zoom of [.75,1,1.25]){const c=await browser.newContext({viewport}),p=await c.newPage();p.setDefaultTimeout(15000);p.on('dialog',d=>d.accept());p.on('pageerror',e=>errors.push(e.stack));await p.route(/^https?:/,r=>{network.push(r.request().url());return r.abort();});const evidence={viewport,browserZoom:1,workbenchZoom:zoom,statements:121,nestingDepth:3};try{
await p.goto(pathToFileURL(L.path.join(dir,manifest.candidate)).href);const source=['1と言う。',...Array(119).fill('何もしない。'),'2と言う。'].join('\n');await p.locator('#codeEditor').fill(source);await p.waitForTimeout(350);await p.locator('#codeEditor').press('Control+End');const before=await state(p);await p.locator('#editorModeblocks').click();const root=p.locator('#blockEditor'),world=root.locator('.blockui-workspace');await root.locator('[data-blockui-action="zoom-reset"]').click();for(let i=0;i<5&&zoom!==1;i++)await root.locator('[data-blockui-action="'+(zoom<1?'zoom-out':'zoom-in')+'"]').click();assert.equal(await root.locator('[data-blockui-action="zoom-reset"]').innerText(),Math.round(zoom*100)+'%');assert.equal((await state(p)).source,source);
const shown=await root.locator('.blockui-statement').evaluateAll(ns=>ns.map(n=>n.dataset.blockId));while(await root.locator('[data-blockui-action="body-gap-next"]').count())await root.locator('[data-blockui-action="body-gap-next"]').first().click();const all=await root.locator('.blockui-statement').evaluateAll(ns=>ns.map(n=>n.dataset.blockId));assert.equal(all.length,121);assert(shown.every(id=>all.includes(id)));assert.equal((await state(p)).history,before.history);
const say=root.locator('.blockui-node[data-schema-id="Say"]'),firstId=await say.first().getAttribute('data-block-id');await U.nodeAction(say.first(),'move');await p.keyboard.press('Escape');assert.equal((await state(p)).source,source);assert.equal((await state(p)).history,before.history);
await U.nodeAction(say.first(),'move');const end=root.locator('.blockui-script > .blockui-node-content > .blockui-body > [data-insert-index="121"]');await tabTo(end);await end.press('Enter');assert.deepEqual((await state(p)).ast.body.filter(n=>n.kind==='Say').map(n=>n.value.value),[2,1]);await p.locator('#undoBtn').click();assert.equal((await state(p)).source,source);await p.locator('#redoBtn').click();assert.deepEqual((await state(p)).ast.body.filter(n=>n.kind==='Say').map(n=>n.value.value),[2,1]);await p.locator('#undoBtn').click();
// A real drag keeps source unchanged while edge scrolling reaches the far end.
// Hover the actual drop target outside the auto-scroll edge bands before reading its preview.
const first=root.locator('[data-block-id="'+firstId+'"].blockui-node');await tabTo(first);const text=first.locator(':scope > .blockui-node-content > .blockui-node-main > .blockui-phrase-text').first();await text.scrollIntoViewIfNeeded();let h=await text.boundingBox(),w=await world.boundingBox();await p.mouse.move(h.x+h.width/2,h.y+h.height/2);await p.mouse.down();await p.mouse.move(h.x+h.width/2+10,h.y+h.height/2,{steps:3});let reached=false;for(let i=0;i<400;i++){w=await world.boundingBox();const d=await end.boundingBox();if(d&&d.y>w.y+10&&d.y+d.height<w.y+w.height-48){await p.mouse.move(Math.max(w.x+32,Math.min(w.x+w.width-32,d.x+25)),d.y+d.height/2);await p.waitForTimeout(50);if(await root.locator('.blockui-drop-preview').count()===1){reached=true;break;}}await p.mouse.move(w.x+Math.min(90,w.width/2),w.y+w.height-7);await p.waitForTimeout(20);}assert(reached,'edge scrolling reaches later loaded page');assert.equal((await state(p)).source,source);assert.equal(await root.locator('.blockui-drop-preview').count(),1);await p.screenshot({path:L.path.join(dir,'workbench-preview-'+viewport.width+'-'+zoom+'.png')});await p.keyboard.press('Escape');await p.mouse.up();assert.equal((await state(p)).source,source);assert.equal((await state(p)).history,before.history);evidence.edgeScrollAndCancel=true;
await p.locator('#editorModecode').click();assert.equal(await p.locator('#codeEditor').inputValue(),source);await p.locator('#codeEditor').fill('次のことを2回くり返す。\n  もし 真なら、次のことをする。\n    次のことを2回くり返す。\n      1＋2＋3＋4＋5＋6＋7＋8＋9＋10と言う。');await p.waitForTimeout(350);await p.locator('#editorModeblocks').click();const nested=root.locator('.blockui-node[data-schema-id="RepeatCount"]').first();await U.nodeAction(nested,'duplicate');await p.locator('#undoBtn').click();await p.locator('#redoBtn').click();assert.equal((await state(p)).ast.body.length,2);await U.nodeAction(nested,'annotations');await nested.locator(':scope > .blockui-node-content > .blockui-annotations [data-blockui-annotation="inlineComment"]').fill('※ 囲い');await root.locator('[data-blockui-action="commit"]').click();await U.nodeAction(nested,'move-down');await p.locator('#undoBtn').click();await p.locator('#redoBtn').click();assert((await state(p)).source.includes('※ 囲い'));
const keep=await state(p);await root.locator('[data-blockui-action="workspace-expand"]').click();await root.locator('[data-blockui-action="library-toggle"]').click();await root.locator('[data-blockui-action="library-toggle"]').click();await root.locator('[data-blockui-action="workspace-expand"]').click();assert.equal((await state(p)).source,keep.source);assert.equal((await state(p)).history,keep.history);await p.locator('#runBtn').click();await p.locator('#stopBtn').click();assert.equal((await state(p)).source,keep.source);await p.screenshot({path:L.path.join(dir,'workbench-final-'+viewport.width+'-'+zoom+'.png')});results.push({pass:true,evidence});
}catch(e){results.push({pass:false,evidence,error:e.stack});await p.screenshot({path:L.path.join(dir,'workbench-fail-'+viewport.width+'-'+zoom+'.png')});}finally{await c.close();L.result(L.path.join(dir,'workbench-matrix.json'),{manifest,browser:browser.version(),results,errors,network});}}
}finally{await browser.close();}console.log(JSON.stringify({passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass).length,errors,network}));if(results.some(x=>!x.pass)||errors.length||network.length)process.exitCode=1;})().catch(e=>{console.error(e);process.exitCode=1;});
